
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CountryOptions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model CountryOptions
 * 
 */
export type CountryOptionsModel = runtime.Types.Result.DefaultSelection<Prisma.$CountryOptionsPayload>

export type AggregateCountryOptions = {
  _count: CountryOptionsCountAggregateOutputType | null
  _avg: CountryOptionsAvgAggregateOutputType | null
  _sum: CountryOptionsSumAggregateOutputType | null
  _min: CountryOptionsMinAggregateOutputType | null
  _max: CountryOptionsMaxAggregateOutputType | null
}

export type CountryOptionsAvgAggregateOutputType = {
  id: number | null
  organizationId: number | null
}

export type CountryOptionsSumAggregateOutputType = {
  id: number | null
  organizationId: number | null
}

export type CountryOptionsMinAggregateOutputType = {
  id: number | null
  organizationId: number | null
  countryCode: string | null
  language: string | null
  countryName: string | null
  allowed: boolean | null
  blocked: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CountryOptionsMaxAggregateOutputType = {
  id: number | null
  organizationId: number | null
  countryCode: string | null
  language: string | null
  countryName: string | null
  allowed: boolean | null
  blocked: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CountryOptionsCountAggregateOutputType = {
  id: number
  organizationId: number
  countryCode: number
  language: number
  countryName: number
  allowed: number
  blocked: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CountryOptionsAvgAggregateInputType = {
  id?: true
  organizationId?: true
}

export type CountryOptionsSumAggregateInputType = {
  id?: true
  organizationId?: true
}

export type CountryOptionsMinAggregateInputType = {
  id?: true
  organizationId?: true
  countryCode?: true
  language?: true
  countryName?: true
  allowed?: true
  blocked?: true
  createdAt?: true
  updatedAt?: true
}

export type CountryOptionsMaxAggregateInputType = {
  id?: true
  organizationId?: true
  countryCode?: true
  language?: true
  countryName?: true
  allowed?: true
  blocked?: true
  createdAt?: true
  updatedAt?: true
}

export type CountryOptionsCountAggregateInputType = {
  id?: true
  organizationId?: true
  countryCode?: true
  language?: true
  countryName?: true
  allowed?: true
  blocked?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CountryOptionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CountryOptions to aggregate.
   */
  where?: Prisma.CountryOptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CountryOptions to fetch.
   */
  orderBy?: Prisma.CountryOptionsOrderByWithRelationInput | Prisma.CountryOptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CountryOptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CountryOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CountryOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CountryOptions
  **/
  _count?: true | CountryOptionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CountryOptionsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CountryOptionsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CountryOptionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CountryOptionsMaxAggregateInputType
}

export type GetCountryOptionsAggregateType<T extends CountryOptionsAggregateArgs> = {
      [P in keyof T & keyof AggregateCountryOptions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCountryOptions[P]>
    : Prisma.GetScalarType<T[P], AggregateCountryOptions[P]>
}




export type CountryOptionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CountryOptionsWhereInput
  orderBy?: Prisma.CountryOptionsOrderByWithAggregationInput | Prisma.CountryOptionsOrderByWithAggregationInput[]
  by: Prisma.CountryOptionsScalarFieldEnum[] | Prisma.CountryOptionsScalarFieldEnum
  having?: Prisma.CountryOptionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CountryOptionsCountAggregateInputType | true
  _avg?: CountryOptionsAvgAggregateInputType
  _sum?: CountryOptionsSumAggregateInputType
  _min?: CountryOptionsMinAggregateInputType
  _max?: CountryOptionsMaxAggregateInputType
}

export type CountryOptionsGroupByOutputType = {
  id: number
  organizationId: number
  countryCode: string
  language: string
  countryName: string
  allowed: boolean
  blocked: boolean
  createdAt: Date
  updatedAt: Date
  _count: CountryOptionsCountAggregateOutputType | null
  _avg: CountryOptionsAvgAggregateOutputType | null
  _sum: CountryOptionsSumAggregateOutputType | null
  _min: CountryOptionsMinAggregateOutputType | null
  _max: CountryOptionsMaxAggregateOutputType | null
}

type GetCountryOptionsGroupByPayload<T extends CountryOptionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CountryOptionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CountryOptionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CountryOptionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CountryOptionsGroupByOutputType[P]>
      }
    >
  >



export type CountryOptionsWhereInput = {
  AND?: Prisma.CountryOptionsWhereInput | Prisma.CountryOptionsWhereInput[]
  OR?: Prisma.CountryOptionsWhereInput[]
  NOT?: Prisma.CountryOptionsWhereInput | Prisma.CountryOptionsWhereInput[]
  id?: Prisma.IntFilter<"CountryOptions"> | number
  organizationId?: Prisma.IntFilter<"CountryOptions"> | number
  countryCode?: Prisma.StringFilter<"CountryOptions"> | string
  language?: Prisma.StringFilter<"CountryOptions"> | string
  countryName?: Prisma.StringFilter<"CountryOptions"> | string
  allowed?: Prisma.BoolFilter<"CountryOptions"> | boolean
  blocked?: Prisma.BoolFilter<"CountryOptions"> | boolean
  createdAt?: Prisma.DateTimeFilter<"CountryOptions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CountryOptions"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
}

export type CountryOptionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  countryCode?: Prisma.SortOrder
  language?: Prisma.SortOrder
  countryName?: Prisma.SortOrder
  allowed?: Prisma.SortOrder
  blocked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  organization?: Prisma.OrganizationOrderByWithRelationInput
}

export type CountryOptionsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  organizationId_countryCode?: Prisma.CountryOptionsOrganizationIdCountryCodeCompoundUniqueInput
  AND?: Prisma.CountryOptionsWhereInput | Prisma.CountryOptionsWhereInput[]
  OR?: Prisma.CountryOptionsWhereInput[]
  NOT?: Prisma.CountryOptionsWhereInput | Prisma.CountryOptionsWhereInput[]
  organizationId?: Prisma.IntFilter<"CountryOptions"> | number
  countryCode?: Prisma.StringFilter<"CountryOptions"> | string
  language?: Prisma.StringFilter<"CountryOptions"> | string
  countryName?: Prisma.StringFilter<"CountryOptions"> | string
  allowed?: Prisma.BoolFilter<"CountryOptions"> | boolean
  blocked?: Prisma.BoolFilter<"CountryOptions"> | boolean
  createdAt?: Prisma.DateTimeFilter<"CountryOptions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CountryOptions"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
}, "id" | "organizationId_countryCode">

export type CountryOptionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  countryCode?: Prisma.SortOrder
  language?: Prisma.SortOrder
  countryName?: Prisma.SortOrder
  allowed?: Prisma.SortOrder
  blocked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CountryOptionsCountOrderByAggregateInput
  _avg?: Prisma.CountryOptionsAvgOrderByAggregateInput
  _max?: Prisma.CountryOptionsMaxOrderByAggregateInput
  _min?: Prisma.CountryOptionsMinOrderByAggregateInput
  _sum?: Prisma.CountryOptionsSumOrderByAggregateInput
}

export type CountryOptionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.CountryOptionsScalarWhereWithAggregatesInput | Prisma.CountryOptionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.CountryOptionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CountryOptionsScalarWhereWithAggregatesInput | Prisma.CountryOptionsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"CountryOptions"> | number
  organizationId?: Prisma.IntWithAggregatesFilter<"CountryOptions"> | number
  countryCode?: Prisma.StringWithAggregatesFilter<"CountryOptions"> | string
  language?: Prisma.StringWithAggregatesFilter<"CountryOptions"> | string
  countryName?: Prisma.StringWithAggregatesFilter<"CountryOptions"> | string
  allowed?: Prisma.BoolWithAggregatesFilter<"CountryOptions"> | boolean
  blocked?: Prisma.BoolWithAggregatesFilter<"CountryOptions"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CountryOptions"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CountryOptions"> | Date | string
}

export type CountryOptionsCreateInput = {
  countryCode: string
  language: string
  countryName: string
  allowed?: boolean
  blocked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutCountryOptionsInput
}

export type CountryOptionsUncheckedCreateInput = {
  id?: number
  organizationId: number
  countryCode: string
  language: string
  countryName: string
  allowed?: boolean
  blocked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CountryOptionsUpdateInput = {
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  countryName?: Prisma.StringFieldUpdateOperationsInput | string
  allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutCountryOptionsNestedInput
}

export type CountryOptionsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  organizationId?: Prisma.IntFieldUpdateOperationsInput | number
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  countryName?: Prisma.StringFieldUpdateOperationsInput | string
  allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountryOptionsCreateManyInput = {
  id?: number
  organizationId: number
  countryCode: string
  language: string
  countryName: string
  allowed?: boolean
  blocked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CountryOptionsUpdateManyMutationInput = {
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  countryName?: Prisma.StringFieldUpdateOperationsInput | string
  allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountryOptionsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  organizationId?: Prisma.IntFieldUpdateOperationsInput | number
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  countryName?: Prisma.StringFieldUpdateOperationsInput | string
  allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountryOptionsListRelationFilter = {
  every?: Prisma.CountryOptionsWhereInput
  some?: Prisma.CountryOptionsWhereInput
  none?: Prisma.CountryOptionsWhereInput
}

export type CountryOptionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CountryOptionsOrganizationIdCountryCodeCompoundUniqueInput = {
  organizationId: number
  countryCode: string
}

export type CountryOptionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  countryCode?: Prisma.SortOrder
  language?: Prisma.SortOrder
  countryName?: Prisma.SortOrder
  allowed?: Prisma.SortOrder
  blocked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CountryOptionsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
}

export type CountryOptionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  countryCode?: Prisma.SortOrder
  language?: Prisma.SortOrder
  countryName?: Prisma.SortOrder
  allowed?: Prisma.SortOrder
  blocked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CountryOptionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  countryCode?: Prisma.SortOrder
  language?: Prisma.SortOrder
  countryName?: Prisma.SortOrder
  allowed?: Prisma.SortOrder
  blocked?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CountryOptionsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
}

export type CountryOptionsCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.CountryOptionsCreateWithoutOrganizationInput, Prisma.CountryOptionsUncheckedCreateWithoutOrganizationInput> | Prisma.CountryOptionsCreateWithoutOrganizationInput[] | Prisma.CountryOptionsUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.CountryOptionsCreateOrConnectWithoutOrganizationInput | Prisma.CountryOptionsCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.CountryOptionsCreateManyOrganizationInputEnvelope
  connect?: Prisma.CountryOptionsWhereUniqueInput | Prisma.CountryOptionsWhereUniqueInput[]
}

export type CountryOptionsUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.CountryOptionsCreateWithoutOrganizationInput, Prisma.CountryOptionsUncheckedCreateWithoutOrganizationInput> | Prisma.CountryOptionsCreateWithoutOrganizationInput[] | Prisma.CountryOptionsUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.CountryOptionsCreateOrConnectWithoutOrganizationInput | Prisma.CountryOptionsCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.CountryOptionsCreateManyOrganizationInputEnvelope
  connect?: Prisma.CountryOptionsWhereUniqueInput | Prisma.CountryOptionsWhereUniqueInput[]
}

export type CountryOptionsUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.CountryOptionsCreateWithoutOrganizationInput, Prisma.CountryOptionsUncheckedCreateWithoutOrganizationInput> | Prisma.CountryOptionsCreateWithoutOrganizationInput[] | Prisma.CountryOptionsUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.CountryOptionsCreateOrConnectWithoutOrganizationInput | Prisma.CountryOptionsCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.CountryOptionsUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.CountryOptionsUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.CountryOptionsCreateManyOrganizationInputEnvelope
  set?: Prisma.CountryOptionsWhereUniqueInput | Prisma.CountryOptionsWhereUniqueInput[]
  disconnect?: Prisma.CountryOptionsWhereUniqueInput | Prisma.CountryOptionsWhereUniqueInput[]
  delete?: Prisma.CountryOptionsWhereUniqueInput | Prisma.CountryOptionsWhereUniqueInput[]
  connect?: Prisma.CountryOptionsWhereUniqueInput | Prisma.CountryOptionsWhereUniqueInput[]
  update?: Prisma.CountryOptionsUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.CountryOptionsUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.CountryOptionsUpdateManyWithWhereWithoutOrganizationInput | Prisma.CountryOptionsUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.CountryOptionsScalarWhereInput | Prisma.CountryOptionsScalarWhereInput[]
}

export type CountryOptionsUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.CountryOptionsCreateWithoutOrganizationInput, Prisma.CountryOptionsUncheckedCreateWithoutOrganizationInput> | Prisma.CountryOptionsCreateWithoutOrganizationInput[] | Prisma.CountryOptionsUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.CountryOptionsCreateOrConnectWithoutOrganizationInput | Prisma.CountryOptionsCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.CountryOptionsUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.CountryOptionsUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.CountryOptionsCreateManyOrganizationInputEnvelope
  set?: Prisma.CountryOptionsWhereUniqueInput | Prisma.CountryOptionsWhereUniqueInput[]
  disconnect?: Prisma.CountryOptionsWhereUniqueInput | Prisma.CountryOptionsWhereUniqueInput[]
  delete?: Prisma.CountryOptionsWhereUniqueInput | Prisma.CountryOptionsWhereUniqueInput[]
  connect?: Prisma.CountryOptionsWhereUniqueInput | Prisma.CountryOptionsWhereUniqueInput[]
  update?: Prisma.CountryOptionsUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.CountryOptionsUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.CountryOptionsUpdateManyWithWhereWithoutOrganizationInput | Prisma.CountryOptionsUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.CountryOptionsScalarWhereInput | Prisma.CountryOptionsScalarWhereInput[]
}

export type CountryOptionsCreateWithoutOrganizationInput = {
  countryCode: string
  language: string
  countryName: string
  allowed?: boolean
  blocked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CountryOptionsUncheckedCreateWithoutOrganizationInput = {
  id?: number
  countryCode: string
  language: string
  countryName: string
  allowed?: boolean
  blocked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CountryOptionsCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.CountryOptionsWhereUniqueInput
  create: Prisma.XOR<Prisma.CountryOptionsCreateWithoutOrganizationInput, Prisma.CountryOptionsUncheckedCreateWithoutOrganizationInput>
}

export type CountryOptionsCreateManyOrganizationInputEnvelope = {
  data: Prisma.CountryOptionsCreateManyOrganizationInput | Prisma.CountryOptionsCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type CountryOptionsUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.CountryOptionsWhereUniqueInput
  update: Prisma.XOR<Prisma.CountryOptionsUpdateWithoutOrganizationInput, Prisma.CountryOptionsUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.CountryOptionsCreateWithoutOrganizationInput, Prisma.CountryOptionsUncheckedCreateWithoutOrganizationInput>
}

export type CountryOptionsUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.CountryOptionsWhereUniqueInput
  data: Prisma.XOR<Prisma.CountryOptionsUpdateWithoutOrganizationInput, Prisma.CountryOptionsUncheckedUpdateWithoutOrganizationInput>
}

export type CountryOptionsUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.CountryOptionsScalarWhereInput
  data: Prisma.XOR<Prisma.CountryOptionsUpdateManyMutationInput, Prisma.CountryOptionsUncheckedUpdateManyWithoutOrganizationInput>
}

export type CountryOptionsScalarWhereInput = {
  AND?: Prisma.CountryOptionsScalarWhereInput | Prisma.CountryOptionsScalarWhereInput[]
  OR?: Prisma.CountryOptionsScalarWhereInput[]
  NOT?: Prisma.CountryOptionsScalarWhereInput | Prisma.CountryOptionsScalarWhereInput[]
  id?: Prisma.IntFilter<"CountryOptions"> | number
  organizationId?: Prisma.IntFilter<"CountryOptions"> | number
  countryCode?: Prisma.StringFilter<"CountryOptions"> | string
  language?: Prisma.StringFilter<"CountryOptions"> | string
  countryName?: Prisma.StringFilter<"CountryOptions"> | string
  allowed?: Prisma.BoolFilter<"CountryOptions"> | boolean
  blocked?: Prisma.BoolFilter<"CountryOptions"> | boolean
  createdAt?: Prisma.DateTimeFilter<"CountryOptions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CountryOptions"> | Date | string
}

export type CountryOptionsCreateManyOrganizationInput = {
  id?: number
  countryCode: string
  language: string
  countryName: string
  allowed?: boolean
  blocked?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CountryOptionsUpdateWithoutOrganizationInput = {
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  countryName?: Prisma.StringFieldUpdateOperationsInput | string
  allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountryOptionsUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  countryName?: Prisma.StringFieldUpdateOperationsInput | string
  allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountryOptionsUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  countryName?: Prisma.StringFieldUpdateOperationsInput | string
  allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CountryOptionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  countryCode?: boolean
  language?: boolean
  countryName?: boolean
  allowed?: boolean
  blocked?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["countryOptions"]>

export type CountryOptionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  countryCode?: boolean
  language?: boolean
  countryName?: boolean
  allowed?: boolean
  blocked?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["countryOptions"]>

export type CountryOptionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  countryCode?: boolean
  language?: boolean
  countryName?: boolean
  allowed?: boolean
  blocked?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["countryOptions"]>

export type CountryOptionsSelectScalar = {
  id?: boolean
  organizationId?: boolean
  countryCode?: boolean
  language?: boolean
  countryName?: boolean
  allowed?: boolean
  blocked?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CountryOptionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "organizationId" | "countryCode" | "language" | "countryName" | "allowed" | "blocked" | "createdAt" | "updatedAt", ExtArgs["result"]["countryOptions"]>
export type CountryOptionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}
export type CountryOptionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}
export type CountryOptionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}

export type $CountryOptionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CountryOptions"
  objects: {
    organization: Prisma.$OrganizationPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    organizationId: number
    countryCode: string
    language: string
    countryName: string
    allowed: boolean
    blocked: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["countryOptions"]>
  composites: {}
}

export type CountryOptionsGetPayload<S extends boolean | null | undefined | CountryOptionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload, S>

export type CountryOptionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CountryOptionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CountryOptionsCountAggregateInputType | true
  }

export interface CountryOptionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CountryOptions'], meta: { name: 'CountryOptions' } }
  /**
   * Find zero or one CountryOptions that matches the filter.
   * @param {CountryOptionsFindUniqueArgs} args - Arguments to find a CountryOptions
   * @example
   * // Get one CountryOptions
   * const countryOptions = await prisma.countryOptions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CountryOptionsFindUniqueArgs>(args: Prisma.SelectSubset<T, CountryOptionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CountryOptionsClient<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CountryOptions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CountryOptionsFindUniqueOrThrowArgs} args - Arguments to find a CountryOptions
   * @example
   * // Get one CountryOptions
   * const countryOptions = await prisma.countryOptions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CountryOptionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CountryOptionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CountryOptionsClient<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CountryOptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryOptionsFindFirstArgs} args - Arguments to find a CountryOptions
   * @example
   * // Get one CountryOptions
   * const countryOptions = await prisma.countryOptions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CountryOptionsFindFirstArgs>(args?: Prisma.SelectSubset<T, CountryOptionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__CountryOptionsClient<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CountryOptions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryOptionsFindFirstOrThrowArgs} args - Arguments to find a CountryOptions
   * @example
   * // Get one CountryOptions
   * const countryOptions = await prisma.countryOptions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CountryOptionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CountryOptionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CountryOptionsClient<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CountryOptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryOptionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CountryOptions
   * const countryOptions = await prisma.countryOptions.findMany()
   * 
   * // Get first 10 CountryOptions
   * const countryOptions = await prisma.countryOptions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const countryOptionsWithIdOnly = await prisma.countryOptions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CountryOptionsFindManyArgs>(args?: Prisma.SelectSubset<T, CountryOptionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CountryOptions.
   * @param {CountryOptionsCreateArgs} args - Arguments to create a CountryOptions.
   * @example
   * // Create one CountryOptions
   * const CountryOptions = await prisma.countryOptions.create({
   *   data: {
   *     // ... data to create a CountryOptions
   *   }
   * })
   * 
   */
  create<T extends CountryOptionsCreateArgs>(args: Prisma.SelectSubset<T, CountryOptionsCreateArgs<ExtArgs>>): Prisma.Prisma__CountryOptionsClient<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CountryOptions.
   * @param {CountryOptionsCreateManyArgs} args - Arguments to create many CountryOptions.
   * @example
   * // Create many CountryOptions
   * const countryOptions = await prisma.countryOptions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CountryOptionsCreateManyArgs>(args?: Prisma.SelectSubset<T, CountryOptionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CountryOptions and returns the data saved in the database.
   * @param {CountryOptionsCreateManyAndReturnArgs} args - Arguments to create many CountryOptions.
   * @example
   * // Create many CountryOptions
   * const countryOptions = await prisma.countryOptions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CountryOptions and only return the `id`
   * const countryOptionsWithIdOnly = await prisma.countryOptions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CountryOptionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CountryOptionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CountryOptions.
   * @param {CountryOptionsDeleteArgs} args - Arguments to delete one CountryOptions.
   * @example
   * // Delete one CountryOptions
   * const CountryOptions = await prisma.countryOptions.delete({
   *   where: {
   *     // ... filter to delete one CountryOptions
   *   }
   * })
   * 
   */
  delete<T extends CountryOptionsDeleteArgs>(args: Prisma.SelectSubset<T, CountryOptionsDeleteArgs<ExtArgs>>): Prisma.Prisma__CountryOptionsClient<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CountryOptions.
   * @param {CountryOptionsUpdateArgs} args - Arguments to update one CountryOptions.
   * @example
   * // Update one CountryOptions
   * const countryOptions = await prisma.countryOptions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CountryOptionsUpdateArgs>(args: Prisma.SelectSubset<T, CountryOptionsUpdateArgs<ExtArgs>>): Prisma.Prisma__CountryOptionsClient<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CountryOptions.
   * @param {CountryOptionsDeleteManyArgs} args - Arguments to filter CountryOptions to delete.
   * @example
   * // Delete a few CountryOptions
   * const { count } = await prisma.countryOptions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CountryOptionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, CountryOptionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CountryOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryOptionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CountryOptions
   * const countryOptions = await prisma.countryOptions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CountryOptionsUpdateManyArgs>(args: Prisma.SelectSubset<T, CountryOptionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CountryOptions and returns the data updated in the database.
   * @param {CountryOptionsUpdateManyAndReturnArgs} args - Arguments to update many CountryOptions.
   * @example
   * // Update many CountryOptions
   * const countryOptions = await prisma.countryOptions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CountryOptions and only return the `id`
   * const countryOptionsWithIdOnly = await prisma.countryOptions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CountryOptionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CountryOptionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CountryOptions.
   * @param {CountryOptionsUpsertArgs} args - Arguments to update or create a CountryOptions.
   * @example
   * // Update or create a CountryOptions
   * const countryOptions = await prisma.countryOptions.upsert({
   *   create: {
   *     // ... data to create a CountryOptions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CountryOptions we want to update
   *   }
   * })
   */
  upsert<T extends CountryOptionsUpsertArgs>(args: Prisma.SelectSubset<T, CountryOptionsUpsertArgs<ExtArgs>>): Prisma.Prisma__CountryOptionsClient<runtime.Types.Result.GetResult<Prisma.$CountryOptionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CountryOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryOptionsCountArgs} args - Arguments to filter CountryOptions to count.
   * @example
   * // Count the number of CountryOptions
   * const count = await prisma.countryOptions.count({
   *   where: {
   *     // ... the filter for the CountryOptions we want to count
   *   }
   * })
  **/
  count<T extends CountryOptionsCountArgs>(
    args?: Prisma.Subset<T, CountryOptionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CountryOptionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CountryOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryOptionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CountryOptionsAggregateArgs>(args: Prisma.Subset<T, CountryOptionsAggregateArgs>): Prisma.PrismaPromise<GetCountryOptionsAggregateType<T>>

  /**
   * Group by CountryOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryOptionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CountryOptionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CountryOptionsGroupByArgs['orderBy'] }
      : { orderBy?: CountryOptionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CountryOptionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCountryOptionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CountryOptions model
 */
readonly fields: CountryOptionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CountryOptions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CountryOptionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  organization<T extends Prisma.OrganizationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDefaultArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CountryOptions model
 */
export interface CountryOptionsFieldRefs {
  readonly id: Prisma.FieldRef<"CountryOptions", 'Int'>
  readonly organizationId: Prisma.FieldRef<"CountryOptions", 'Int'>
  readonly countryCode: Prisma.FieldRef<"CountryOptions", 'String'>
  readonly language: Prisma.FieldRef<"CountryOptions", 'String'>
  readonly countryName: Prisma.FieldRef<"CountryOptions", 'String'>
  readonly allowed: Prisma.FieldRef<"CountryOptions", 'Boolean'>
  readonly blocked: Prisma.FieldRef<"CountryOptions", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"CountryOptions", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CountryOptions", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CountryOptions findUnique
 */
export type CountryOptionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsInclude<ExtArgs> | null
  /**
   * Filter, which CountryOptions to fetch.
   */
  where: Prisma.CountryOptionsWhereUniqueInput
}

/**
 * CountryOptions findUniqueOrThrow
 */
export type CountryOptionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsInclude<ExtArgs> | null
  /**
   * Filter, which CountryOptions to fetch.
   */
  where: Prisma.CountryOptionsWhereUniqueInput
}

/**
 * CountryOptions findFirst
 */
export type CountryOptionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsInclude<ExtArgs> | null
  /**
   * Filter, which CountryOptions to fetch.
   */
  where?: Prisma.CountryOptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CountryOptions to fetch.
   */
  orderBy?: Prisma.CountryOptionsOrderByWithRelationInput | Prisma.CountryOptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CountryOptions.
   */
  cursor?: Prisma.CountryOptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CountryOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CountryOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CountryOptions.
   */
  distinct?: Prisma.CountryOptionsScalarFieldEnum | Prisma.CountryOptionsScalarFieldEnum[]
}

/**
 * CountryOptions findFirstOrThrow
 */
export type CountryOptionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsInclude<ExtArgs> | null
  /**
   * Filter, which CountryOptions to fetch.
   */
  where?: Prisma.CountryOptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CountryOptions to fetch.
   */
  orderBy?: Prisma.CountryOptionsOrderByWithRelationInput | Prisma.CountryOptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CountryOptions.
   */
  cursor?: Prisma.CountryOptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CountryOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CountryOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CountryOptions.
   */
  distinct?: Prisma.CountryOptionsScalarFieldEnum | Prisma.CountryOptionsScalarFieldEnum[]
}

/**
 * CountryOptions findMany
 */
export type CountryOptionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsInclude<ExtArgs> | null
  /**
   * Filter, which CountryOptions to fetch.
   */
  where?: Prisma.CountryOptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CountryOptions to fetch.
   */
  orderBy?: Prisma.CountryOptionsOrderByWithRelationInput | Prisma.CountryOptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CountryOptions.
   */
  cursor?: Prisma.CountryOptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CountryOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CountryOptions.
   */
  skip?: number
  distinct?: Prisma.CountryOptionsScalarFieldEnum | Prisma.CountryOptionsScalarFieldEnum[]
}

/**
 * CountryOptions create
 */
export type CountryOptionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsInclude<ExtArgs> | null
  /**
   * The data needed to create a CountryOptions.
   */
  data: Prisma.XOR<Prisma.CountryOptionsCreateInput, Prisma.CountryOptionsUncheckedCreateInput>
}

/**
 * CountryOptions createMany
 */
export type CountryOptionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CountryOptions.
   */
  data: Prisma.CountryOptionsCreateManyInput | Prisma.CountryOptionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CountryOptions createManyAndReturn
 */
export type CountryOptionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * The data used to create many CountryOptions.
   */
  data: Prisma.CountryOptionsCreateManyInput | Prisma.CountryOptionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CountryOptions update
 */
export type CountryOptionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsInclude<ExtArgs> | null
  /**
   * The data needed to update a CountryOptions.
   */
  data: Prisma.XOR<Prisma.CountryOptionsUpdateInput, Prisma.CountryOptionsUncheckedUpdateInput>
  /**
   * Choose, which CountryOptions to update.
   */
  where: Prisma.CountryOptionsWhereUniqueInput
}

/**
 * CountryOptions updateMany
 */
export type CountryOptionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CountryOptions.
   */
  data: Prisma.XOR<Prisma.CountryOptionsUpdateManyMutationInput, Prisma.CountryOptionsUncheckedUpdateManyInput>
  /**
   * Filter which CountryOptions to update
   */
  where?: Prisma.CountryOptionsWhereInput
  /**
   * Limit how many CountryOptions to update.
   */
  limit?: number
}

/**
 * CountryOptions updateManyAndReturn
 */
export type CountryOptionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * The data used to update CountryOptions.
   */
  data: Prisma.XOR<Prisma.CountryOptionsUpdateManyMutationInput, Prisma.CountryOptionsUncheckedUpdateManyInput>
  /**
   * Filter which CountryOptions to update
   */
  where?: Prisma.CountryOptionsWhereInput
  /**
   * Limit how many CountryOptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CountryOptions upsert
 */
export type CountryOptionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsInclude<ExtArgs> | null
  /**
   * The filter to search for the CountryOptions to update in case it exists.
   */
  where: Prisma.CountryOptionsWhereUniqueInput
  /**
   * In case the CountryOptions found by the `where` argument doesn't exist, create a new CountryOptions with this data.
   */
  create: Prisma.XOR<Prisma.CountryOptionsCreateInput, Prisma.CountryOptionsUncheckedCreateInput>
  /**
   * In case the CountryOptions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CountryOptionsUpdateInput, Prisma.CountryOptionsUncheckedUpdateInput>
}

/**
 * CountryOptions delete
 */
export type CountryOptionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsInclude<ExtArgs> | null
  /**
   * Filter which CountryOptions to delete.
   */
  where: Prisma.CountryOptionsWhereUniqueInput
}

/**
 * CountryOptions deleteMany
 */
export type CountryOptionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CountryOptions to delete
   */
  where?: Prisma.CountryOptionsWhereInput
  /**
   * Limit how many CountryOptions to delete.
   */
  limit?: number
}

/**
 * CountryOptions without action
 */
export type CountryOptionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryOptions
   */
  select?: Prisma.CountryOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryOptions
   */
  omit?: Prisma.CountryOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryOptionsInclude<ExtArgs> | null
}
