
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Demography` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Demography
 * 
 */
export type DemographyModel = runtime.Types.Result.DefaultSelection<Prisma.$DemographyPayload>

export type AggregateDemography = {
  _count: DemographyCountAggregateOutputType | null
  _avg: DemographyAvgAggregateOutputType | null
  _sum: DemographySumAggregateOutputType | null
  _min: DemographyMinAggregateOutputType | null
  _max: DemographyMaxAggregateOutputType | null
}

export type DemographyAvgAggregateOutputType = {
  id: number | null
}

export type DemographySumAggregateOutputType = {
  id: number | null
}

export type DemographyMinAggregateOutputType = {
  id: number | null
  name: string | null
  slug: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DemographyMaxAggregateOutputType = {
  id: number | null
  name: string | null
  slug: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DemographyCountAggregateOutputType = {
  id: number
  name: number
  slug: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DemographyAvgAggregateInputType = {
  id?: true
}

export type DemographySumAggregateInputType = {
  id?: true
}

export type DemographyMinAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type DemographyMaxAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type DemographyCountAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DemographyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Demography to aggregate.
   */
  where?: Prisma.DemographyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Demographies to fetch.
   */
  orderBy?: Prisma.DemographyOrderByWithRelationInput | Prisma.DemographyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DemographyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Demographies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Demographies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Demographies
  **/
  _count?: true | DemographyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DemographyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DemographySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DemographyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DemographyMaxAggregateInputType
}

export type GetDemographyAggregateType<T extends DemographyAggregateArgs> = {
      [P in keyof T & keyof AggregateDemography]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDemography[P]>
    : Prisma.GetScalarType<T[P], AggregateDemography[P]>
}




export type DemographyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DemographyWhereInput
  orderBy?: Prisma.DemographyOrderByWithAggregationInput | Prisma.DemographyOrderByWithAggregationInput[]
  by: Prisma.DemographyScalarFieldEnum[] | Prisma.DemographyScalarFieldEnum
  having?: Prisma.DemographyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DemographyCountAggregateInputType | true
  _avg?: DemographyAvgAggregateInputType
  _sum?: DemographySumAggregateInputType
  _min?: DemographyMinAggregateInputType
  _max?: DemographyMaxAggregateInputType
}

export type DemographyGroupByOutputType = {
  id: number
  name: string
  slug: string
  description: string
  createdAt: Date
  updatedAt: Date
  _count: DemographyCountAggregateOutputType | null
  _avg: DemographyAvgAggregateOutputType | null
  _sum: DemographySumAggregateOutputType | null
  _min: DemographyMinAggregateOutputType | null
  _max: DemographyMaxAggregateOutputType | null
}

type GetDemographyGroupByPayload<T extends DemographyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DemographyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DemographyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DemographyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DemographyGroupByOutputType[P]>
      }
    >
  >



export type DemographyWhereInput = {
  AND?: Prisma.DemographyWhereInput | Prisma.DemographyWhereInput[]
  OR?: Prisma.DemographyWhereInput[]
  NOT?: Prisma.DemographyWhereInput | Prisma.DemographyWhereInput[]
  id?: Prisma.IntFilter<"Demography"> | number
  name?: Prisma.StringFilter<"Demography"> | string
  slug?: Prisma.StringFilter<"Demography"> | string
  description?: Prisma.StringFilter<"Demography"> | string
  createdAt?: Prisma.DateTimeFilter<"Demography"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Demography"> | Date | string
  mangas?: Prisma.MangaListRelationFilter
}

export type DemographyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mangas?: Prisma.MangaOrderByRelationAggregateInput
}

export type DemographyWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  name?: string
  slug?: string
  AND?: Prisma.DemographyWhereInput | Prisma.DemographyWhereInput[]
  OR?: Prisma.DemographyWhereInput[]
  NOT?: Prisma.DemographyWhereInput | Prisma.DemographyWhereInput[]
  description?: Prisma.StringFilter<"Demography"> | string
  createdAt?: Prisma.DateTimeFilter<"Demography"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Demography"> | Date | string
  mangas?: Prisma.MangaListRelationFilter
}, "id" | "name" | "slug">

export type DemographyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DemographyCountOrderByAggregateInput
  _avg?: Prisma.DemographyAvgOrderByAggregateInput
  _max?: Prisma.DemographyMaxOrderByAggregateInput
  _min?: Prisma.DemographyMinOrderByAggregateInput
  _sum?: Prisma.DemographySumOrderByAggregateInput
}

export type DemographyScalarWhereWithAggregatesInput = {
  AND?: Prisma.DemographyScalarWhereWithAggregatesInput | Prisma.DemographyScalarWhereWithAggregatesInput[]
  OR?: Prisma.DemographyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DemographyScalarWhereWithAggregatesInput | Prisma.DemographyScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Demography"> | number
  name?: Prisma.StringWithAggregatesFilter<"Demography"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Demography"> | string
  description?: Prisma.StringWithAggregatesFilter<"Demography"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Demography"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Demography"> | Date | string
}

export type DemographyCreateInput = {
  name: string
  slug: string
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  mangas?: Prisma.MangaCreateNestedManyWithoutDemographyInput
}

export type DemographyUncheckedCreateInput = {
  id?: number
  name: string
  slug: string
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  mangas?: Prisma.MangaUncheckedCreateNestedManyWithoutDemographyInput
}

export type DemographyUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mangas?: Prisma.MangaUpdateManyWithoutDemographyNestedInput
}

export type DemographyUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mangas?: Prisma.MangaUncheckedUpdateManyWithoutDemographyNestedInput
}

export type DemographyCreateManyInput = {
  id?: number
  name: string
  slug: string
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemographyUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemographyUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemographyScalarRelationFilter = {
  is?: Prisma.DemographyWhereInput
  isNot?: Prisma.DemographyWhereInput
}

export type DemographyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DemographyAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DemographyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DemographyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DemographySumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DemographyCreateNestedOneWithoutMangasInput = {
  create?: Prisma.XOR<Prisma.DemographyCreateWithoutMangasInput, Prisma.DemographyUncheckedCreateWithoutMangasInput>
  connectOrCreate?: Prisma.DemographyCreateOrConnectWithoutMangasInput
  connect?: Prisma.DemographyWhereUniqueInput
}

export type DemographyUpdateOneRequiredWithoutMangasNestedInput = {
  create?: Prisma.XOR<Prisma.DemographyCreateWithoutMangasInput, Prisma.DemographyUncheckedCreateWithoutMangasInput>
  connectOrCreate?: Prisma.DemographyCreateOrConnectWithoutMangasInput
  upsert?: Prisma.DemographyUpsertWithoutMangasInput
  connect?: Prisma.DemographyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DemographyUpdateToOneWithWhereWithoutMangasInput, Prisma.DemographyUpdateWithoutMangasInput>, Prisma.DemographyUncheckedUpdateWithoutMangasInput>
}

export type DemographyCreateWithoutMangasInput = {
  name: string
  slug: string
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemographyUncheckedCreateWithoutMangasInput = {
  id?: number
  name: string
  slug: string
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemographyCreateOrConnectWithoutMangasInput = {
  where: Prisma.DemographyWhereUniqueInput
  create: Prisma.XOR<Prisma.DemographyCreateWithoutMangasInput, Prisma.DemographyUncheckedCreateWithoutMangasInput>
}

export type DemographyUpsertWithoutMangasInput = {
  update: Prisma.XOR<Prisma.DemographyUpdateWithoutMangasInput, Prisma.DemographyUncheckedUpdateWithoutMangasInput>
  create: Prisma.XOR<Prisma.DemographyCreateWithoutMangasInput, Prisma.DemographyUncheckedCreateWithoutMangasInput>
  where?: Prisma.DemographyWhereInput
}

export type DemographyUpdateToOneWithWhereWithoutMangasInput = {
  where?: Prisma.DemographyWhereInput
  data: Prisma.XOR<Prisma.DemographyUpdateWithoutMangasInput, Prisma.DemographyUncheckedUpdateWithoutMangasInput>
}

export type DemographyUpdateWithoutMangasInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemographyUncheckedUpdateWithoutMangasInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type DemographyCountOutputType
 */

export type DemographyCountOutputType = {
  mangas: number
}

export type DemographyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mangas?: boolean | DemographyCountOutputTypeCountMangasArgs
}

/**
 * DemographyCountOutputType without action
 */
export type DemographyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemographyCountOutputType
   */
  select?: Prisma.DemographyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DemographyCountOutputType without action
 */
export type DemographyCountOutputTypeCountMangasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MangaWhereInput
}


export type DemographySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mangas?: boolean | Prisma.Demography$mangasArgs<ExtArgs>
  _count?: boolean | Prisma.DemographyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["demography"]>

export type DemographySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["demography"]>

export type DemographySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["demography"]>

export type DemographySelectScalar = {
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DemographyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "slug" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["demography"]>
export type DemographyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mangas?: boolean | Prisma.Demography$mangasArgs<ExtArgs>
  _count?: boolean | Prisma.DemographyCountOutputTypeDefaultArgs<ExtArgs>
}
export type DemographyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type DemographyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $DemographyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Demography"
  objects: {
    mangas: Prisma.$MangaPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    slug: string
    description: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["demography"]>
  composites: {}
}

export type DemographyGetPayload<S extends boolean | null | undefined | DemographyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DemographyPayload, S>

export type DemographyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DemographyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DemographyCountAggregateInputType | true
  }

export interface DemographyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Demography'], meta: { name: 'Demography' } }
  /**
   * Find zero or one Demography that matches the filter.
   * @param {DemographyFindUniqueArgs} args - Arguments to find a Demography
   * @example
   * // Get one Demography
   * const demography = await prisma.demography.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DemographyFindUniqueArgs>(args: Prisma.SelectSubset<T, DemographyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DemographyClient<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Demography that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DemographyFindUniqueOrThrowArgs} args - Arguments to find a Demography
   * @example
   * // Get one Demography
   * const demography = await prisma.demography.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DemographyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DemographyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DemographyClient<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Demography that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemographyFindFirstArgs} args - Arguments to find a Demography
   * @example
   * // Get one Demography
   * const demography = await prisma.demography.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DemographyFindFirstArgs>(args?: Prisma.SelectSubset<T, DemographyFindFirstArgs<ExtArgs>>): Prisma.Prisma__DemographyClient<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Demography that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemographyFindFirstOrThrowArgs} args - Arguments to find a Demography
   * @example
   * // Get one Demography
   * const demography = await prisma.demography.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DemographyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DemographyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DemographyClient<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Demographies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemographyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Demographies
   * const demographies = await prisma.demography.findMany()
   * 
   * // Get first 10 Demographies
   * const demographies = await prisma.demography.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const demographyWithIdOnly = await prisma.demography.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DemographyFindManyArgs>(args?: Prisma.SelectSubset<T, DemographyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Demography.
   * @param {DemographyCreateArgs} args - Arguments to create a Demography.
   * @example
   * // Create one Demography
   * const Demography = await prisma.demography.create({
   *   data: {
   *     // ... data to create a Demography
   *   }
   * })
   * 
   */
  create<T extends DemographyCreateArgs>(args: Prisma.SelectSubset<T, DemographyCreateArgs<ExtArgs>>): Prisma.Prisma__DemographyClient<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Demographies.
   * @param {DemographyCreateManyArgs} args - Arguments to create many Demographies.
   * @example
   * // Create many Demographies
   * const demography = await prisma.demography.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DemographyCreateManyArgs>(args?: Prisma.SelectSubset<T, DemographyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Demographies and returns the data saved in the database.
   * @param {DemographyCreateManyAndReturnArgs} args - Arguments to create many Demographies.
   * @example
   * // Create many Demographies
   * const demography = await prisma.demography.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Demographies and only return the `id`
   * const demographyWithIdOnly = await prisma.demography.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DemographyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DemographyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Demography.
   * @param {DemographyDeleteArgs} args - Arguments to delete one Demography.
   * @example
   * // Delete one Demography
   * const Demography = await prisma.demography.delete({
   *   where: {
   *     // ... filter to delete one Demography
   *   }
   * })
   * 
   */
  delete<T extends DemographyDeleteArgs>(args: Prisma.SelectSubset<T, DemographyDeleteArgs<ExtArgs>>): Prisma.Prisma__DemographyClient<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Demography.
   * @param {DemographyUpdateArgs} args - Arguments to update one Demography.
   * @example
   * // Update one Demography
   * const demography = await prisma.demography.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DemographyUpdateArgs>(args: Prisma.SelectSubset<T, DemographyUpdateArgs<ExtArgs>>): Prisma.Prisma__DemographyClient<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Demographies.
   * @param {DemographyDeleteManyArgs} args - Arguments to filter Demographies to delete.
   * @example
   * // Delete a few Demographies
   * const { count } = await prisma.demography.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DemographyDeleteManyArgs>(args?: Prisma.SelectSubset<T, DemographyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Demographies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemographyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Demographies
   * const demography = await prisma.demography.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DemographyUpdateManyArgs>(args: Prisma.SelectSubset<T, DemographyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Demographies and returns the data updated in the database.
   * @param {DemographyUpdateManyAndReturnArgs} args - Arguments to update many Demographies.
   * @example
   * // Update many Demographies
   * const demography = await prisma.demography.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Demographies and only return the `id`
   * const demographyWithIdOnly = await prisma.demography.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DemographyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DemographyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Demography.
   * @param {DemographyUpsertArgs} args - Arguments to update or create a Demography.
   * @example
   * // Update or create a Demography
   * const demography = await prisma.demography.upsert({
   *   create: {
   *     // ... data to create a Demography
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Demography we want to update
   *   }
   * })
   */
  upsert<T extends DemographyUpsertArgs>(args: Prisma.SelectSubset<T, DemographyUpsertArgs<ExtArgs>>): Prisma.Prisma__DemographyClient<runtime.Types.Result.GetResult<Prisma.$DemographyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Demographies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemographyCountArgs} args - Arguments to filter Demographies to count.
   * @example
   * // Count the number of Demographies
   * const count = await prisma.demography.count({
   *   where: {
   *     // ... the filter for the Demographies we want to count
   *   }
   * })
  **/
  count<T extends DemographyCountArgs>(
    args?: Prisma.Subset<T, DemographyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DemographyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Demography.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemographyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DemographyAggregateArgs>(args: Prisma.Subset<T, DemographyAggregateArgs>): Prisma.PrismaPromise<GetDemographyAggregateType<T>>

  /**
   * Group by Demography.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemographyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DemographyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DemographyGroupByArgs['orderBy'] }
      : { orderBy?: DemographyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DemographyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDemographyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Demography model
 */
readonly fields: DemographyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Demography.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DemographyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mangas<T extends Prisma.Demography$mangasArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Demography$mangasArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MangaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Demography model
 */
export interface DemographyFieldRefs {
  readonly id: Prisma.FieldRef<"Demography", 'Int'>
  readonly name: Prisma.FieldRef<"Demography", 'String'>
  readonly slug: Prisma.FieldRef<"Demography", 'String'>
  readonly description: Prisma.FieldRef<"Demography", 'String'>
  readonly createdAt: Prisma.FieldRef<"Demography", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Demography", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Demography findUnique
 */
export type DemographyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemographyInclude<ExtArgs> | null
  /**
   * Filter, which Demography to fetch.
   */
  where: Prisma.DemographyWhereUniqueInput
}

/**
 * Demography findUniqueOrThrow
 */
export type DemographyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemographyInclude<ExtArgs> | null
  /**
   * Filter, which Demography to fetch.
   */
  where: Prisma.DemographyWhereUniqueInput
}

/**
 * Demography findFirst
 */
export type DemographyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemographyInclude<ExtArgs> | null
  /**
   * Filter, which Demography to fetch.
   */
  where?: Prisma.DemographyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Demographies to fetch.
   */
  orderBy?: Prisma.DemographyOrderByWithRelationInput | Prisma.DemographyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Demographies.
   */
  cursor?: Prisma.DemographyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Demographies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Demographies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Demographies.
   */
  distinct?: Prisma.DemographyScalarFieldEnum | Prisma.DemographyScalarFieldEnum[]
}

/**
 * Demography findFirstOrThrow
 */
export type DemographyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemographyInclude<ExtArgs> | null
  /**
   * Filter, which Demography to fetch.
   */
  where?: Prisma.DemographyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Demographies to fetch.
   */
  orderBy?: Prisma.DemographyOrderByWithRelationInput | Prisma.DemographyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Demographies.
   */
  cursor?: Prisma.DemographyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Demographies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Demographies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Demographies.
   */
  distinct?: Prisma.DemographyScalarFieldEnum | Prisma.DemographyScalarFieldEnum[]
}

/**
 * Demography findMany
 */
export type DemographyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemographyInclude<ExtArgs> | null
  /**
   * Filter, which Demographies to fetch.
   */
  where?: Prisma.DemographyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Demographies to fetch.
   */
  orderBy?: Prisma.DemographyOrderByWithRelationInput | Prisma.DemographyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Demographies.
   */
  cursor?: Prisma.DemographyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Demographies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Demographies.
   */
  skip?: number
  distinct?: Prisma.DemographyScalarFieldEnum | Prisma.DemographyScalarFieldEnum[]
}

/**
 * Demography create
 */
export type DemographyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemographyInclude<ExtArgs> | null
  /**
   * The data needed to create a Demography.
   */
  data: Prisma.XOR<Prisma.DemographyCreateInput, Prisma.DemographyUncheckedCreateInput>
}

/**
 * Demography createMany
 */
export type DemographyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Demographies.
   */
  data: Prisma.DemographyCreateManyInput | Prisma.DemographyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Demography createManyAndReturn
 */
export type DemographyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * The data used to create many Demographies.
   */
  data: Prisma.DemographyCreateManyInput | Prisma.DemographyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Demography update
 */
export type DemographyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemographyInclude<ExtArgs> | null
  /**
   * The data needed to update a Demography.
   */
  data: Prisma.XOR<Prisma.DemographyUpdateInput, Prisma.DemographyUncheckedUpdateInput>
  /**
   * Choose, which Demography to update.
   */
  where: Prisma.DemographyWhereUniqueInput
}

/**
 * Demography updateMany
 */
export type DemographyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Demographies.
   */
  data: Prisma.XOR<Prisma.DemographyUpdateManyMutationInput, Prisma.DemographyUncheckedUpdateManyInput>
  /**
   * Filter which Demographies to update
   */
  where?: Prisma.DemographyWhereInput
  /**
   * Limit how many Demographies to update.
   */
  limit?: number
}

/**
 * Demography updateManyAndReturn
 */
export type DemographyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * The data used to update Demographies.
   */
  data: Prisma.XOR<Prisma.DemographyUpdateManyMutationInput, Prisma.DemographyUncheckedUpdateManyInput>
  /**
   * Filter which Demographies to update
   */
  where?: Prisma.DemographyWhereInput
  /**
   * Limit how many Demographies to update.
   */
  limit?: number
}

/**
 * Demography upsert
 */
export type DemographyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemographyInclude<ExtArgs> | null
  /**
   * The filter to search for the Demography to update in case it exists.
   */
  where: Prisma.DemographyWhereUniqueInput
  /**
   * In case the Demography found by the `where` argument doesn't exist, create a new Demography with this data.
   */
  create: Prisma.XOR<Prisma.DemographyCreateInput, Prisma.DemographyUncheckedCreateInput>
  /**
   * In case the Demography was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DemographyUpdateInput, Prisma.DemographyUncheckedUpdateInput>
}

/**
 * Demography delete
 */
export type DemographyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemographyInclude<ExtArgs> | null
  /**
   * Filter which Demography to delete.
   */
  where: Prisma.DemographyWhereUniqueInput
}

/**
 * Demography deleteMany
 */
export type DemographyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Demographies to delete
   */
  where?: Prisma.DemographyWhereInput
  /**
   * Limit how many Demographies to delete.
   */
  limit?: number
}

/**
 * Demography.mangas
 */
export type Demography$mangasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manga
   */
  select?: Prisma.MangaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manga
   */
  omit?: Prisma.MangaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MangaInclude<ExtArgs> | null
  where?: Prisma.MangaWhereInput
  orderBy?: Prisma.MangaOrderByWithRelationInput | Prisma.MangaOrderByWithRelationInput[]
  cursor?: Prisma.MangaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MangaScalarFieldEnum | Prisma.MangaScalarFieldEnum[]
}

/**
 * Demography without action
 */
export type DemographyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Demography
   */
  select?: Prisma.DemographySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Demography
   */
  omit?: Prisma.DemographyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemographyInclude<ExtArgs> | null
}
