
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ModerationLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ModerationLog
 * 
 */
export type ModerationLogModel = runtime.Types.Result.DefaultSelection<Prisma.$ModerationLogPayload>

export type AggregateModerationLog = {
  _count: ModerationLogCountAggregateOutputType | null
  _avg: ModerationLogAvgAggregateOutputType | null
  _sum: ModerationLogSumAggregateOutputType | null
  _min: ModerationLogMinAggregateOutputType | null
  _max: ModerationLogMaxAggregateOutputType | null
}

export type ModerationLogAvgAggregateOutputType = {
  id: number | null
  actorUserId: number | null
  targetId: number | null
}

export type ModerationLogSumAggregateOutputType = {
  id: number | null
  actorUserId: number | null
  targetId: number | null
}

export type ModerationLogMinAggregateOutputType = {
  id: number | null
  actorUserId: number | null
  action: string | null
  targetType: string | null
  targetId: number | null
  details: string | null
  createdAt: Date | null
}

export type ModerationLogMaxAggregateOutputType = {
  id: number | null
  actorUserId: number | null
  action: string | null
  targetType: string | null
  targetId: number | null
  details: string | null
  createdAt: Date | null
}

export type ModerationLogCountAggregateOutputType = {
  id: number
  actorUserId: number
  action: number
  targetType: number
  targetId: number
  details: number
  createdAt: number
  _all: number
}


export type ModerationLogAvgAggregateInputType = {
  id?: true
  actorUserId?: true
  targetId?: true
}

export type ModerationLogSumAggregateInputType = {
  id?: true
  actorUserId?: true
  targetId?: true
}

export type ModerationLogMinAggregateInputType = {
  id?: true
  actorUserId?: true
  action?: true
  targetType?: true
  targetId?: true
  details?: true
  createdAt?: true
}

export type ModerationLogMaxAggregateInputType = {
  id?: true
  actorUserId?: true
  action?: true
  targetType?: true
  targetId?: true
  details?: true
  createdAt?: true
}

export type ModerationLogCountAggregateInputType = {
  id?: true
  actorUserId?: true
  action?: true
  targetType?: true
  targetId?: true
  details?: true
  createdAt?: true
  _all?: true
}

export type ModerationLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModerationLog to aggregate.
   */
  where?: Prisma.ModerationLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationLogs to fetch.
   */
  orderBy?: Prisma.ModerationLogOrderByWithRelationInput | Prisma.ModerationLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ModerationLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ModerationLogs
  **/
  _count?: true | ModerationLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ModerationLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ModerationLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ModerationLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ModerationLogMaxAggregateInputType
}

export type GetModerationLogAggregateType<T extends ModerationLogAggregateArgs> = {
      [P in keyof T & keyof AggregateModerationLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateModerationLog[P]>
    : Prisma.GetScalarType<T[P], AggregateModerationLog[P]>
}




export type ModerationLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModerationLogWhereInput
  orderBy?: Prisma.ModerationLogOrderByWithAggregationInput | Prisma.ModerationLogOrderByWithAggregationInput[]
  by: Prisma.ModerationLogScalarFieldEnum[] | Prisma.ModerationLogScalarFieldEnum
  having?: Prisma.ModerationLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ModerationLogCountAggregateInputType | true
  _avg?: ModerationLogAvgAggregateInputType
  _sum?: ModerationLogSumAggregateInputType
  _min?: ModerationLogMinAggregateInputType
  _max?: ModerationLogMaxAggregateInputType
}

export type ModerationLogGroupByOutputType = {
  id: number
  actorUserId: number | null
  action: string
  targetType: string
  targetId: number
  details: string | null
  createdAt: Date
  _count: ModerationLogCountAggregateOutputType | null
  _avg: ModerationLogAvgAggregateOutputType | null
  _sum: ModerationLogSumAggregateOutputType | null
  _min: ModerationLogMinAggregateOutputType | null
  _max: ModerationLogMaxAggregateOutputType | null
}

type GetModerationLogGroupByPayload<T extends ModerationLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ModerationLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ModerationLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ModerationLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ModerationLogGroupByOutputType[P]>
      }
    >
  >



export type ModerationLogWhereInput = {
  AND?: Prisma.ModerationLogWhereInput | Prisma.ModerationLogWhereInput[]
  OR?: Prisma.ModerationLogWhereInput[]
  NOT?: Prisma.ModerationLogWhereInput | Prisma.ModerationLogWhereInput[]
  id?: Prisma.IntFilter<"ModerationLog"> | number
  actorUserId?: Prisma.IntNullableFilter<"ModerationLog"> | number | null
  action?: Prisma.StringFilter<"ModerationLog"> | string
  targetType?: Prisma.StringFilter<"ModerationLog"> | string
  targetId?: Prisma.IntFilter<"ModerationLog"> | number
  details?: Prisma.StringNullableFilter<"ModerationLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ModerationLog"> | Date | string
  actor?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type ModerationLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  actorUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  action?: Prisma.SortOrder
  targetType?: Prisma.SortOrder
  targetId?: Prisma.SortOrder
  details?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  actor?: Prisma.UserOrderByWithRelationInput
}

export type ModerationLogWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ModerationLogWhereInput | Prisma.ModerationLogWhereInput[]
  OR?: Prisma.ModerationLogWhereInput[]
  NOT?: Prisma.ModerationLogWhereInput | Prisma.ModerationLogWhereInput[]
  actorUserId?: Prisma.IntNullableFilter<"ModerationLog"> | number | null
  action?: Prisma.StringFilter<"ModerationLog"> | string
  targetType?: Prisma.StringFilter<"ModerationLog"> | string
  targetId?: Prisma.IntFilter<"ModerationLog"> | number
  details?: Prisma.StringNullableFilter<"ModerationLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ModerationLog"> | Date | string
  actor?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type ModerationLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  actorUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  action?: Prisma.SortOrder
  targetType?: Prisma.SortOrder
  targetId?: Prisma.SortOrder
  details?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ModerationLogCountOrderByAggregateInput
  _avg?: Prisma.ModerationLogAvgOrderByAggregateInput
  _max?: Prisma.ModerationLogMaxOrderByAggregateInput
  _min?: Prisma.ModerationLogMinOrderByAggregateInput
  _sum?: Prisma.ModerationLogSumOrderByAggregateInput
}

export type ModerationLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.ModerationLogScalarWhereWithAggregatesInput | Prisma.ModerationLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.ModerationLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ModerationLogScalarWhereWithAggregatesInput | Prisma.ModerationLogScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ModerationLog"> | number
  actorUserId?: Prisma.IntNullableWithAggregatesFilter<"ModerationLog"> | number | null
  action?: Prisma.StringWithAggregatesFilter<"ModerationLog"> | string
  targetType?: Prisma.StringWithAggregatesFilter<"ModerationLog"> | string
  targetId?: Prisma.IntWithAggregatesFilter<"ModerationLog"> | number
  details?: Prisma.StringNullableWithAggregatesFilter<"ModerationLog"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ModerationLog"> | Date | string
}

export type ModerationLogCreateInput = {
  action: string
  targetType: string
  targetId: number
  details?: string | null
  createdAt?: Date | string
  actor?: Prisma.UserCreateNestedOneWithoutModerationLogsInput
}

export type ModerationLogUncheckedCreateInput = {
  id?: number
  actorUserId?: number | null
  action: string
  targetType: string
  targetId: number
  details?: string | null
  createdAt?: Date | string
}

export type ModerationLogUpdateInput = {
  action?: Prisma.StringFieldUpdateOperationsInput | string
  targetType?: Prisma.StringFieldUpdateOperationsInput | string
  targetId?: Prisma.IntFieldUpdateOperationsInput | number
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actor?: Prisma.UserUpdateOneWithoutModerationLogsNestedInput
}

export type ModerationLogUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  actorUserId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  action?: Prisma.StringFieldUpdateOperationsInput | string
  targetType?: Prisma.StringFieldUpdateOperationsInput | string
  targetId?: Prisma.IntFieldUpdateOperationsInput | number
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationLogCreateManyInput = {
  id?: number
  actorUserId?: number | null
  action: string
  targetType: string
  targetId: number
  details?: string | null
  createdAt?: Date | string
}

export type ModerationLogUpdateManyMutationInput = {
  action?: Prisma.StringFieldUpdateOperationsInput | string
  targetType?: Prisma.StringFieldUpdateOperationsInput | string
  targetId?: Prisma.IntFieldUpdateOperationsInput | number
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationLogUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  actorUserId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  action?: Prisma.StringFieldUpdateOperationsInput | string
  targetType?: Prisma.StringFieldUpdateOperationsInput | string
  targetId?: Prisma.IntFieldUpdateOperationsInput | number
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationLogListRelationFilter = {
  every?: Prisma.ModerationLogWhereInput
  some?: Prisma.ModerationLogWhereInput
  none?: Prisma.ModerationLogWhereInput
}

export type ModerationLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ModerationLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actorUserId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  targetType?: Prisma.SortOrder
  targetId?: Prisma.SortOrder
  details?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ModerationLogAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actorUserId?: Prisma.SortOrder
  targetId?: Prisma.SortOrder
}

export type ModerationLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actorUserId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  targetType?: Prisma.SortOrder
  targetId?: Prisma.SortOrder
  details?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ModerationLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actorUserId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  targetType?: Prisma.SortOrder
  targetId?: Prisma.SortOrder
  details?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ModerationLogSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actorUserId?: Prisma.SortOrder
  targetId?: Prisma.SortOrder
}

export type ModerationLogCreateNestedManyWithoutActorInput = {
  create?: Prisma.XOR<Prisma.ModerationLogCreateWithoutActorInput, Prisma.ModerationLogUncheckedCreateWithoutActorInput> | Prisma.ModerationLogCreateWithoutActorInput[] | Prisma.ModerationLogUncheckedCreateWithoutActorInput[]
  connectOrCreate?: Prisma.ModerationLogCreateOrConnectWithoutActorInput | Prisma.ModerationLogCreateOrConnectWithoutActorInput[]
  createMany?: Prisma.ModerationLogCreateManyActorInputEnvelope
  connect?: Prisma.ModerationLogWhereUniqueInput | Prisma.ModerationLogWhereUniqueInput[]
}

export type ModerationLogUncheckedCreateNestedManyWithoutActorInput = {
  create?: Prisma.XOR<Prisma.ModerationLogCreateWithoutActorInput, Prisma.ModerationLogUncheckedCreateWithoutActorInput> | Prisma.ModerationLogCreateWithoutActorInput[] | Prisma.ModerationLogUncheckedCreateWithoutActorInput[]
  connectOrCreate?: Prisma.ModerationLogCreateOrConnectWithoutActorInput | Prisma.ModerationLogCreateOrConnectWithoutActorInput[]
  createMany?: Prisma.ModerationLogCreateManyActorInputEnvelope
  connect?: Prisma.ModerationLogWhereUniqueInput | Prisma.ModerationLogWhereUniqueInput[]
}

export type ModerationLogUpdateManyWithoutActorNestedInput = {
  create?: Prisma.XOR<Prisma.ModerationLogCreateWithoutActorInput, Prisma.ModerationLogUncheckedCreateWithoutActorInput> | Prisma.ModerationLogCreateWithoutActorInput[] | Prisma.ModerationLogUncheckedCreateWithoutActorInput[]
  connectOrCreate?: Prisma.ModerationLogCreateOrConnectWithoutActorInput | Prisma.ModerationLogCreateOrConnectWithoutActorInput[]
  upsert?: Prisma.ModerationLogUpsertWithWhereUniqueWithoutActorInput | Prisma.ModerationLogUpsertWithWhereUniqueWithoutActorInput[]
  createMany?: Prisma.ModerationLogCreateManyActorInputEnvelope
  set?: Prisma.ModerationLogWhereUniqueInput | Prisma.ModerationLogWhereUniqueInput[]
  disconnect?: Prisma.ModerationLogWhereUniqueInput | Prisma.ModerationLogWhereUniqueInput[]
  delete?: Prisma.ModerationLogWhereUniqueInput | Prisma.ModerationLogWhereUniqueInput[]
  connect?: Prisma.ModerationLogWhereUniqueInput | Prisma.ModerationLogWhereUniqueInput[]
  update?: Prisma.ModerationLogUpdateWithWhereUniqueWithoutActorInput | Prisma.ModerationLogUpdateWithWhereUniqueWithoutActorInput[]
  updateMany?: Prisma.ModerationLogUpdateManyWithWhereWithoutActorInput | Prisma.ModerationLogUpdateManyWithWhereWithoutActorInput[]
  deleteMany?: Prisma.ModerationLogScalarWhereInput | Prisma.ModerationLogScalarWhereInput[]
}

export type ModerationLogUncheckedUpdateManyWithoutActorNestedInput = {
  create?: Prisma.XOR<Prisma.ModerationLogCreateWithoutActorInput, Prisma.ModerationLogUncheckedCreateWithoutActorInput> | Prisma.ModerationLogCreateWithoutActorInput[] | Prisma.ModerationLogUncheckedCreateWithoutActorInput[]
  connectOrCreate?: Prisma.ModerationLogCreateOrConnectWithoutActorInput | Prisma.ModerationLogCreateOrConnectWithoutActorInput[]
  upsert?: Prisma.ModerationLogUpsertWithWhereUniqueWithoutActorInput | Prisma.ModerationLogUpsertWithWhereUniqueWithoutActorInput[]
  createMany?: Prisma.ModerationLogCreateManyActorInputEnvelope
  set?: Prisma.ModerationLogWhereUniqueInput | Prisma.ModerationLogWhereUniqueInput[]
  disconnect?: Prisma.ModerationLogWhereUniqueInput | Prisma.ModerationLogWhereUniqueInput[]
  delete?: Prisma.ModerationLogWhereUniqueInput | Prisma.ModerationLogWhereUniqueInput[]
  connect?: Prisma.ModerationLogWhereUniqueInput | Prisma.ModerationLogWhereUniqueInput[]
  update?: Prisma.ModerationLogUpdateWithWhereUniqueWithoutActorInput | Prisma.ModerationLogUpdateWithWhereUniqueWithoutActorInput[]
  updateMany?: Prisma.ModerationLogUpdateManyWithWhereWithoutActorInput | Prisma.ModerationLogUpdateManyWithWhereWithoutActorInput[]
  deleteMany?: Prisma.ModerationLogScalarWhereInput | Prisma.ModerationLogScalarWhereInput[]
}

export type ModerationLogCreateWithoutActorInput = {
  action: string
  targetType: string
  targetId: number
  details?: string | null
  createdAt?: Date | string
}

export type ModerationLogUncheckedCreateWithoutActorInput = {
  id?: number
  action: string
  targetType: string
  targetId: number
  details?: string | null
  createdAt?: Date | string
}

export type ModerationLogCreateOrConnectWithoutActorInput = {
  where: Prisma.ModerationLogWhereUniqueInput
  create: Prisma.XOR<Prisma.ModerationLogCreateWithoutActorInput, Prisma.ModerationLogUncheckedCreateWithoutActorInput>
}

export type ModerationLogCreateManyActorInputEnvelope = {
  data: Prisma.ModerationLogCreateManyActorInput | Prisma.ModerationLogCreateManyActorInput[]
  skipDuplicates?: boolean
}

export type ModerationLogUpsertWithWhereUniqueWithoutActorInput = {
  where: Prisma.ModerationLogWhereUniqueInput
  update: Prisma.XOR<Prisma.ModerationLogUpdateWithoutActorInput, Prisma.ModerationLogUncheckedUpdateWithoutActorInput>
  create: Prisma.XOR<Prisma.ModerationLogCreateWithoutActorInput, Prisma.ModerationLogUncheckedCreateWithoutActorInput>
}

export type ModerationLogUpdateWithWhereUniqueWithoutActorInput = {
  where: Prisma.ModerationLogWhereUniqueInput
  data: Prisma.XOR<Prisma.ModerationLogUpdateWithoutActorInput, Prisma.ModerationLogUncheckedUpdateWithoutActorInput>
}

export type ModerationLogUpdateManyWithWhereWithoutActorInput = {
  where: Prisma.ModerationLogScalarWhereInput
  data: Prisma.XOR<Prisma.ModerationLogUpdateManyMutationInput, Prisma.ModerationLogUncheckedUpdateManyWithoutActorInput>
}

export type ModerationLogScalarWhereInput = {
  AND?: Prisma.ModerationLogScalarWhereInput | Prisma.ModerationLogScalarWhereInput[]
  OR?: Prisma.ModerationLogScalarWhereInput[]
  NOT?: Prisma.ModerationLogScalarWhereInput | Prisma.ModerationLogScalarWhereInput[]
  id?: Prisma.IntFilter<"ModerationLog"> | number
  actorUserId?: Prisma.IntNullableFilter<"ModerationLog"> | number | null
  action?: Prisma.StringFilter<"ModerationLog"> | string
  targetType?: Prisma.StringFilter<"ModerationLog"> | string
  targetId?: Prisma.IntFilter<"ModerationLog"> | number
  details?: Prisma.StringNullableFilter<"ModerationLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ModerationLog"> | Date | string
}

export type ModerationLogCreateManyActorInput = {
  id?: number
  action: string
  targetType: string
  targetId: number
  details?: string | null
  createdAt?: Date | string
}

export type ModerationLogUpdateWithoutActorInput = {
  action?: Prisma.StringFieldUpdateOperationsInput | string
  targetType?: Prisma.StringFieldUpdateOperationsInput | string
  targetId?: Prisma.IntFieldUpdateOperationsInput | number
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationLogUncheckedUpdateWithoutActorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  action?: Prisma.StringFieldUpdateOperationsInput | string
  targetType?: Prisma.StringFieldUpdateOperationsInput | string
  targetId?: Prisma.IntFieldUpdateOperationsInput | number
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationLogUncheckedUpdateManyWithoutActorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  action?: Prisma.StringFieldUpdateOperationsInput | string
  targetType?: Prisma.StringFieldUpdateOperationsInput | string
  targetId?: Prisma.IntFieldUpdateOperationsInput | number
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ModerationLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  actorUserId?: boolean
  action?: boolean
  targetType?: boolean
  targetId?: boolean
  details?: boolean
  createdAt?: boolean
  actor?: boolean | Prisma.ModerationLog$actorArgs<ExtArgs>
}, ExtArgs["result"]["moderationLog"]>

export type ModerationLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  actorUserId?: boolean
  action?: boolean
  targetType?: boolean
  targetId?: boolean
  details?: boolean
  createdAt?: boolean
  actor?: boolean | Prisma.ModerationLog$actorArgs<ExtArgs>
}, ExtArgs["result"]["moderationLog"]>

export type ModerationLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  actorUserId?: boolean
  action?: boolean
  targetType?: boolean
  targetId?: boolean
  details?: boolean
  createdAt?: boolean
  actor?: boolean | Prisma.ModerationLog$actorArgs<ExtArgs>
}, ExtArgs["result"]["moderationLog"]>

export type ModerationLogSelectScalar = {
  id?: boolean
  actorUserId?: boolean
  action?: boolean
  targetType?: boolean
  targetId?: boolean
  details?: boolean
  createdAt?: boolean
}

export type ModerationLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "actorUserId" | "action" | "targetType" | "targetId" | "details" | "createdAt", ExtArgs["result"]["moderationLog"]>
export type ModerationLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actor?: boolean | Prisma.ModerationLog$actorArgs<ExtArgs>
}
export type ModerationLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actor?: boolean | Prisma.ModerationLog$actorArgs<ExtArgs>
}
export type ModerationLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actor?: boolean | Prisma.ModerationLog$actorArgs<ExtArgs>
}

export type $ModerationLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ModerationLog"
  objects: {
    actor: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    actorUserId: number | null
    action: string
    targetType: string
    targetId: number
    details: string | null
    createdAt: Date
  }, ExtArgs["result"]["moderationLog"]>
  composites: {}
}

export type ModerationLogGetPayload<S extends boolean | null | undefined | ModerationLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload, S>

export type ModerationLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ModerationLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ModerationLogCountAggregateInputType | true
  }

export interface ModerationLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ModerationLog'], meta: { name: 'ModerationLog' } }
  /**
   * Find zero or one ModerationLog that matches the filter.
   * @param {ModerationLogFindUniqueArgs} args - Arguments to find a ModerationLog
   * @example
   * // Get one ModerationLog
   * const moderationLog = await prisma.moderationLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ModerationLogFindUniqueArgs>(args: Prisma.SelectSubset<T, ModerationLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ModerationLogClient<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ModerationLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ModerationLogFindUniqueOrThrowArgs} args - Arguments to find a ModerationLog
   * @example
   * // Get one ModerationLog
   * const moderationLog = await prisma.moderationLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ModerationLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ModerationLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModerationLogClient<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModerationLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationLogFindFirstArgs} args - Arguments to find a ModerationLog
   * @example
   * // Get one ModerationLog
   * const moderationLog = await prisma.moderationLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ModerationLogFindFirstArgs>(args?: Prisma.SelectSubset<T, ModerationLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__ModerationLogClient<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModerationLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationLogFindFirstOrThrowArgs} args - Arguments to find a ModerationLog
   * @example
   * // Get one ModerationLog
   * const moderationLog = await prisma.moderationLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ModerationLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ModerationLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModerationLogClient<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ModerationLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ModerationLogs
   * const moderationLogs = await prisma.moderationLog.findMany()
   * 
   * // Get first 10 ModerationLogs
   * const moderationLogs = await prisma.moderationLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const moderationLogWithIdOnly = await prisma.moderationLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ModerationLogFindManyArgs>(args?: Prisma.SelectSubset<T, ModerationLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ModerationLog.
   * @param {ModerationLogCreateArgs} args - Arguments to create a ModerationLog.
   * @example
   * // Create one ModerationLog
   * const ModerationLog = await prisma.moderationLog.create({
   *   data: {
   *     // ... data to create a ModerationLog
   *   }
   * })
   * 
   */
  create<T extends ModerationLogCreateArgs>(args: Prisma.SelectSubset<T, ModerationLogCreateArgs<ExtArgs>>): Prisma.Prisma__ModerationLogClient<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ModerationLogs.
   * @param {ModerationLogCreateManyArgs} args - Arguments to create many ModerationLogs.
   * @example
   * // Create many ModerationLogs
   * const moderationLog = await prisma.moderationLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ModerationLogCreateManyArgs>(args?: Prisma.SelectSubset<T, ModerationLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ModerationLogs and returns the data saved in the database.
   * @param {ModerationLogCreateManyAndReturnArgs} args - Arguments to create many ModerationLogs.
   * @example
   * // Create many ModerationLogs
   * const moderationLog = await prisma.moderationLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ModerationLogs and only return the `id`
   * const moderationLogWithIdOnly = await prisma.moderationLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ModerationLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ModerationLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ModerationLog.
   * @param {ModerationLogDeleteArgs} args - Arguments to delete one ModerationLog.
   * @example
   * // Delete one ModerationLog
   * const ModerationLog = await prisma.moderationLog.delete({
   *   where: {
   *     // ... filter to delete one ModerationLog
   *   }
   * })
   * 
   */
  delete<T extends ModerationLogDeleteArgs>(args: Prisma.SelectSubset<T, ModerationLogDeleteArgs<ExtArgs>>): Prisma.Prisma__ModerationLogClient<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ModerationLog.
   * @param {ModerationLogUpdateArgs} args - Arguments to update one ModerationLog.
   * @example
   * // Update one ModerationLog
   * const moderationLog = await prisma.moderationLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ModerationLogUpdateArgs>(args: Prisma.SelectSubset<T, ModerationLogUpdateArgs<ExtArgs>>): Prisma.Prisma__ModerationLogClient<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ModerationLogs.
   * @param {ModerationLogDeleteManyArgs} args - Arguments to filter ModerationLogs to delete.
   * @example
   * // Delete a few ModerationLogs
   * const { count } = await prisma.moderationLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ModerationLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, ModerationLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModerationLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ModerationLogs
   * const moderationLog = await prisma.moderationLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ModerationLogUpdateManyArgs>(args: Prisma.SelectSubset<T, ModerationLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModerationLogs and returns the data updated in the database.
   * @param {ModerationLogUpdateManyAndReturnArgs} args - Arguments to update many ModerationLogs.
   * @example
   * // Update many ModerationLogs
   * const moderationLog = await prisma.moderationLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ModerationLogs and only return the `id`
   * const moderationLogWithIdOnly = await prisma.moderationLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ModerationLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ModerationLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ModerationLog.
   * @param {ModerationLogUpsertArgs} args - Arguments to update or create a ModerationLog.
   * @example
   * // Update or create a ModerationLog
   * const moderationLog = await prisma.moderationLog.upsert({
   *   create: {
   *     // ... data to create a ModerationLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ModerationLog we want to update
   *   }
   * })
   */
  upsert<T extends ModerationLogUpsertArgs>(args: Prisma.SelectSubset<T, ModerationLogUpsertArgs<ExtArgs>>): Prisma.Prisma__ModerationLogClient<runtime.Types.Result.GetResult<Prisma.$ModerationLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ModerationLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationLogCountArgs} args - Arguments to filter ModerationLogs to count.
   * @example
   * // Count the number of ModerationLogs
   * const count = await prisma.moderationLog.count({
   *   where: {
   *     // ... the filter for the ModerationLogs we want to count
   *   }
   * })
  **/
  count<T extends ModerationLogCountArgs>(
    args?: Prisma.Subset<T, ModerationLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ModerationLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ModerationLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ModerationLogAggregateArgs>(args: Prisma.Subset<T, ModerationLogAggregateArgs>): Prisma.PrismaPromise<GetModerationLogAggregateType<T>>

  /**
   * Group by ModerationLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ModerationLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ModerationLogGroupByArgs['orderBy'] }
      : { orderBy?: ModerationLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ModerationLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetModerationLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ModerationLog model
 */
readonly fields: ModerationLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ModerationLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ModerationLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  actor<T extends Prisma.ModerationLog$actorArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ModerationLog$actorArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ModerationLog model
 */
export interface ModerationLogFieldRefs {
  readonly id: Prisma.FieldRef<"ModerationLog", 'Int'>
  readonly actorUserId: Prisma.FieldRef<"ModerationLog", 'Int'>
  readonly action: Prisma.FieldRef<"ModerationLog", 'String'>
  readonly targetType: Prisma.FieldRef<"ModerationLog", 'String'>
  readonly targetId: Prisma.FieldRef<"ModerationLog", 'Int'>
  readonly details: Prisma.FieldRef<"ModerationLog", 'String'>
  readonly createdAt: Prisma.FieldRef<"ModerationLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ModerationLog findUnique
 */
export type ModerationLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogInclude<ExtArgs> | null
  /**
   * Filter, which ModerationLog to fetch.
   */
  where: Prisma.ModerationLogWhereUniqueInput
}

/**
 * ModerationLog findUniqueOrThrow
 */
export type ModerationLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogInclude<ExtArgs> | null
  /**
   * Filter, which ModerationLog to fetch.
   */
  where: Prisma.ModerationLogWhereUniqueInput
}

/**
 * ModerationLog findFirst
 */
export type ModerationLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogInclude<ExtArgs> | null
  /**
   * Filter, which ModerationLog to fetch.
   */
  where?: Prisma.ModerationLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationLogs to fetch.
   */
  orderBy?: Prisma.ModerationLogOrderByWithRelationInput | Prisma.ModerationLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModerationLogs.
   */
  cursor?: Prisma.ModerationLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModerationLogs.
   */
  distinct?: Prisma.ModerationLogScalarFieldEnum | Prisma.ModerationLogScalarFieldEnum[]
}

/**
 * ModerationLog findFirstOrThrow
 */
export type ModerationLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogInclude<ExtArgs> | null
  /**
   * Filter, which ModerationLog to fetch.
   */
  where?: Prisma.ModerationLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationLogs to fetch.
   */
  orderBy?: Prisma.ModerationLogOrderByWithRelationInput | Prisma.ModerationLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModerationLogs.
   */
  cursor?: Prisma.ModerationLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModerationLogs.
   */
  distinct?: Prisma.ModerationLogScalarFieldEnum | Prisma.ModerationLogScalarFieldEnum[]
}

/**
 * ModerationLog findMany
 */
export type ModerationLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogInclude<ExtArgs> | null
  /**
   * Filter, which ModerationLogs to fetch.
   */
  where?: Prisma.ModerationLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationLogs to fetch.
   */
  orderBy?: Prisma.ModerationLogOrderByWithRelationInput | Prisma.ModerationLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ModerationLogs.
   */
  cursor?: Prisma.ModerationLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationLogs.
   */
  skip?: number
  distinct?: Prisma.ModerationLogScalarFieldEnum | Prisma.ModerationLogScalarFieldEnum[]
}

/**
 * ModerationLog create
 */
export type ModerationLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogInclude<ExtArgs> | null
  /**
   * The data needed to create a ModerationLog.
   */
  data: Prisma.XOR<Prisma.ModerationLogCreateInput, Prisma.ModerationLogUncheckedCreateInput>
}

/**
 * ModerationLog createMany
 */
export type ModerationLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ModerationLogs.
   */
  data: Prisma.ModerationLogCreateManyInput | Prisma.ModerationLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ModerationLog createManyAndReturn
 */
export type ModerationLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * The data used to create many ModerationLogs.
   */
  data: Prisma.ModerationLogCreateManyInput | Prisma.ModerationLogCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ModerationLog update
 */
export type ModerationLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogInclude<ExtArgs> | null
  /**
   * The data needed to update a ModerationLog.
   */
  data: Prisma.XOR<Prisma.ModerationLogUpdateInput, Prisma.ModerationLogUncheckedUpdateInput>
  /**
   * Choose, which ModerationLog to update.
   */
  where: Prisma.ModerationLogWhereUniqueInput
}

/**
 * ModerationLog updateMany
 */
export type ModerationLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ModerationLogs.
   */
  data: Prisma.XOR<Prisma.ModerationLogUpdateManyMutationInput, Prisma.ModerationLogUncheckedUpdateManyInput>
  /**
   * Filter which ModerationLogs to update
   */
  where?: Prisma.ModerationLogWhereInput
  /**
   * Limit how many ModerationLogs to update.
   */
  limit?: number
}

/**
 * ModerationLog updateManyAndReturn
 */
export type ModerationLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * The data used to update ModerationLogs.
   */
  data: Prisma.XOR<Prisma.ModerationLogUpdateManyMutationInput, Prisma.ModerationLogUncheckedUpdateManyInput>
  /**
   * Filter which ModerationLogs to update
   */
  where?: Prisma.ModerationLogWhereInput
  /**
   * Limit how many ModerationLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ModerationLog upsert
 */
export type ModerationLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogInclude<ExtArgs> | null
  /**
   * The filter to search for the ModerationLog to update in case it exists.
   */
  where: Prisma.ModerationLogWhereUniqueInput
  /**
   * In case the ModerationLog found by the `where` argument doesn't exist, create a new ModerationLog with this data.
   */
  create: Prisma.XOR<Prisma.ModerationLogCreateInput, Prisma.ModerationLogUncheckedCreateInput>
  /**
   * In case the ModerationLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ModerationLogUpdateInput, Prisma.ModerationLogUncheckedUpdateInput>
}

/**
 * ModerationLog delete
 */
export type ModerationLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogInclude<ExtArgs> | null
  /**
   * Filter which ModerationLog to delete.
   */
  where: Prisma.ModerationLogWhereUniqueInput
}

/**
 * ModerationLog deleteMany
 */
export type ModerationLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModerationLogs to delete
   */
  where?: Prisma.ModerationLogWhereInput
  /**
   * Limit how many ModerationLogs to delete.
   */
  limit?: number
}

/**
 * ModerationLog.actor
 */
export type ModerationLog$actorArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * ModerationLog without action
 */
export type ModerationLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationLog
   */
  select?: Prisma.ModerationLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationLog
   */
  omit?: Prisma.ModerationLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationLogInclude<ExtArgs> | null
}
