
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RaffleComment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model RaffleComment
 * 
 */
export type RaffleCommentModel = runtime.Types.Result.DefaultSelection<Prisma.$RaffleCommentPayload>

export type AggregateRaffleComment = {
  _count: RaffleCommentCountAggregateOutputType | null
  _avg: RaffleCommentAvgAggregateOutputType | null
  _sum: RaffleCommentSumAggregateOutputType | null
  _min: RaffleCommentMinAggregateOutputType | null
  _max: RaffleCommentMaxAggregateOutputType | null
}

export type RaffleCommentAvgAggregateOutputType = {
  id: number | null
  raffleId: number | null
  userId: number | null
}

export type RaffleCommentSumAggregateOutputType = {
  id: number | null
  raffleId: number | null
  userId: number | null
}

export type RaffleCommentMinAggregateOutputType = {
  id: number | null
  raffleId: number | null
  userId: number | null
  body: string | null
  createdAt: Date | null
}

export type RaffleCommentMaxAggregateOutputType = {
  id: number | null
  raffleId: number | null
  userId: number | null
  body: string | null
  createdAt: Date | null
}

export type RaffleCommentCountAggregateOutputType = {
  id: number
  raffleId: number
  userId: number
  body: number
  createdAt: number
  _all: number
}


export type RaffleCommentAvgAggregateInputType = {
  id?: true
  raffleId?: true
  userId?: true
}

export type RaffleCommentSumAggregateInputType = {
  id?: true
  raffleId?: true
  userId?: true
}

export type RaffleCommentMinAggregateInputType = {
  id?: true
  raffleId?: true
  userId?: true
  body?: true
  createdAt?: true
}

export type RaffleCommentMaxAggregateInputType = {
  id?: true
  raffleId?: true
  userId?: true
  body?: true
  createdAt?: true
}

export type RaffleCommentCountAggregateInputType = {
  id?: true
  raffleId?: true
  userId?: true
  body?: true
  createdAt?: true
  _all?: true
}

export type RaffleCommentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RaffleComment to aggregate.
   */
  where?: Prisma.RaffleCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RaffleComments to fetch.
   */
  orderBy?: Prisma.RaffleCommentOrderByWithRelationInput | Prisma.RaffleCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RaffleCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RaffleComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RaffleComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RaffleComments
  **/
  _count?: true | RaffleCommentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RaffleCommentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RaffleCommentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RaffleCommentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RaffleCommentMaxAggregateInputType
}

export type GetRaffleCommentAggregateType<T extends RaffleCommentAggregateArgs> = {
      [P in keyof T & keyof AggregateRaffleComment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRaffleComment[P]>
    : Prisma.GetScalarType<T[P], AggregateRaffleComment[P]>
}




export type RaffleCommentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RaffleCommentWhereInput
  orderBy?: Prisma.RaffleCommentOrderByWithAggregationInput | Prisma.RaffleCommentOrderByWithAggregationInput[]
  by: Prisma.RaffleCommentScalarFieldEnum[] | Prisma.RaffleCommentScalarFieldEnum
  having?: Prisma.RaffleCommentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RaffleCommentCountAggregateInputType | true
  _avg?: RaffleCommentAvgAggregateInputType
  _sum?: RaffleCommentSumAggregateInputType
  _min?: RaffleCommentMinAggregateInputType
  _max?: RaffleCommentMaxAggregateInputType
}

export type RaffleCommentGroupByOutputType = {
  id: number
  raffleId: number
  userId: number
  body: string
  createdAt: Date
  _count: RaffleCommentCountAggregateOutputType | null
  _avg: RaffleCommentAvgAggregateOutputType | null
  _sum: RaffleCommentSumAggregateOutputType | null
  _min: RaffleCommentMinAggregateOutputType | null
  _max: RaffleCommentMaxAggregateOutputType | null
}

type GetRaffleCommentGroupByPayload<T extends RaffleCommentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RaffleCommentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RaffleCommentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RaffleCommentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RaffleCommentGroupByOutputType[P]>
      }
    >
  >



export type RaffleCommentWhereInput = {
  AND?: Prisma.RaffleCommentWhereInput | Prisma.RaffleCommentWhereInput[]
  OR?: Prisma.RaffleCommentWhereInput[]
  NOT?: Prisma.RaffleCommentWhereInput | Prisma.RaffleCommentWhereInput[]
  id?: Prisma.IntFilter<"RaffleComment"> | number
  raffleId?: Prisma.IntFilter<"RaffleComment"> | number
  userId?: Prisma.IntFilter<"RaffleComment"> | number
  body?: Prisma.StringFilter<"RaffleComment"> | string
  createdAt?: Prisma.DateTimeFilter<"RaffleComment"> | Date | string
  raffle?: Prisma.XOR<Prisma.RaffleScalarRelationFilter, Prisma.RaffleWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type RaffleCommentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  raffleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  raffle?: Prisma.RaffleOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type RaffleCommentWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.RaffleCommentWhereInput | Prisma.RaffleCommentWhereInput[]
  OR?: Prisma.RaffleCommentWhereInput[]
  NOT?: Prisma.RaffleCommentWhereInput | Prisma.RaffleCommentWhereInput[]
  raffleId?: Prisma.IntFilter<"RaffleComment"> | number
  userId?: Prisma.IntFilter<"RaffleComment"> | number
  body?: Prisma.StringFilter<"RaffleComment"> | string
  createdAt?: Prisma.DateTimeFilter<"RaffleComment"> | Date | string
  raffle?: Prisma.XOR<Prisma.RaffleScalarRelationFilter, Prisma.RaffleWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type RaffleCommentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  raffleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.RaffleCommentCountOrderByAggregateInput
  _avg?: Prisma.RaffleCommentAvgOrderByAggregateInput
  _max?: Prisma.RaffleCommentMaxOrderByAggregateInput
  _min?: Prisma.RaffleCommentMinOrderByAggregateInput
  _sum?: Prisma.RaffleCommentSumOrderByAggregateInput
}

export type RaffleCommentScalarWhereWithAggregatesInput = {
  AND?: Prisma.RaffleCommentScalarWhereWithAggregatesInput | Prisma.RaffleCommentScalarWhereWithAggregatesInput[]
  OR?: Prisma.RaffleCommentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RaffleCommentScalarWhereWithAggregatesInput | Prisma.RaffleCommentScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"RaffleComment"> | number
  raffleId?: Prisma.IntWithAggregatesFilter<"RaffleComment"> | number
  userId?: Prisma.IntWithAggregatesFilter<"RaffleComment"> | number
  body?: Prisma.StringWithAggregatesFilter<"RaffleComment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RaffleComment"> | Date | string
}

export type RaffleCommentCreateInput = {
  body: string
  createdAt?: Date | string
  raffle: Prisma.RaffleCreateNestedOneWithoutCommentsInput
  user: Prisma.UserCreateNestedOneWithoutRaffleCommentsInput
}

export type RaffleCommentUncheckedCreateInput = {
  id?: number
  raffleId: number
  userId: number
  body: string
  createdAt?: Date | string
}

export type RaffleCommentUpdateInput = {
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  raffle?: Prisma.RaffleUpdateOneRequiredWithoutCommentsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutRaffleCommentsNestedInput
}

export type RaffleCommentUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  raffleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RaffleCommentCreateManyInput = {
  id?: number
  raffleId: number
  userId: number
  body: string
  createdAt?: Date | string
}

export type RaffleCommentUpdateManyMutationInput = {
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RaffleCommentUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  raffleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RaffleCommentListRelationFilter = {
  every?: Prisma.RaffleCommentWhereInput
  some?: Prisma.RaffleCommentWhereInput
  none?: Prisma.RaffleCommentWhereInput
}

export type RaffleCommentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RaffleCommentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  raffleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RaffleCommentAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  raffleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type RaffleCommentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  raffleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RaffleCommentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  raffleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RaffleCommentSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  raffleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type RaffleCommentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.RaffleCommentCreateWithoutUserInput, Prisma.RaffleCommentUncheckedCreateWithoutUserInput> | Prisma.RaffleCommentCreateWithoutUserInput[] | Prisma.RaffleCommentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RaffleCommentCreateOrConnectWithoutUserInput | Prisma.RaffleCommentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.RaffleCommentCreateManyUserInputEnvelope
  connect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
}

export type RaffleCommentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.RaffleCommentCreateWithoutUserInput, Prisma.RaffleCommentUncheckedCreateWithoutUserInput> | Prisma.RaffleCommentCreateWithoutUserInput[] | Prisma.RaffleCommentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RaffleCommentCreateOrConnectWithoutUserInput | Prisma.RaffleCommentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.RaffleCommentCreateManyUserInputEnvelope
  connect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
}

export type RaffleCommentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.RaffleCommentCreateWithoutUserInput, Prisma.RaffleCommentUncheckedCreateWithoutUserInput> | Prisma.RaffleCommentCreateWithoutUserInput[] | Prisma.RaffleCommentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RaffleCommentCreateOrConnectWithoutUserInput | Prisma.RaffleCommentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.RaffleCommentUpsertWithWhereUniqueWithoutUserInput | Prisma.RaffleCommentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.RaffleCommentCreateManyUserInputEnvelope
  set?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  disconnect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  delete?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  connect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  update?: Prisma.RaffleCommentUpdateWithWhereUniqueWithoutUserInput | Prisma.RaffleCommentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.RaffleCommentUpdateManyWithWhereWithoutUserInput | Prisma.RaffleCommentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.RaffleCommentScalarWhereInput | Prisma.RaffleCommentScalarWhereInput[]
}

export type RaffleCommentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.RaffleCommentCreateWithoutUserInput, Prisma.RaffleCommentUncheckedCreateWithoutUserInput> | Prisma.RaffleCommentCreateWithoutUserInput[] | Prisma.RaffleCommentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RaffleCommentCreateOrConnectWithoutUserInput | Prisma.RaffleCommentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.RaffleCommentUpsertWithWhereUniqueWithoutUserInput | Prisma.RaffleCommentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.RaffleCommentCreateManyUserInputEnvelope
  set?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  disconnect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  delete?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  connect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  update?: Prisma.RaffleCommentUpdateWithWhereUniqueWithoutUserInput | Prisma.RaffleCommentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.RaffleCommentUpdateManyWithWhereWithoutUserInput | Prisma.RaffleCommentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.RaffleCommentScalarWhereInput | Prisma.RaffleCommentScalarWhereInput[]
}

export type RaffleCommentCreateNestedManyWithoutRaffleInput = {
  create?: Prisma.XOR<Prisma.RaffleCommentCreateWithoutRaffleInput, Prisma.RaffleCommentUncheckedCreateWithoutRaffleInput> | Prisma.RaffleCommentCreateWithoutRaffleInput[] | Prisma.RaffleCommentUncheckedCreateWithoutRaffleInput[]
  connectOrCreate?: Prisma.RaffleCommentCreateOrConnectWithoutRaffleInput | Prisma.RaffleCommentCreateOrConnectWithoutRaffleInput[]
  createMany?: Prisma.RaffleCommentCreateManyRaffleInputEnvelope
  connect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
}

export type RaffleCommentUncheckedCreateNestedManyWithoutRaffleInput = {
  create?: Prisma.XOR<Prisma.RaffleCommentCreateWithoutRaffleInput, Prisma.RaffleCommentUncheckedCreateWithoutRaffleInput> | Prisma.RaffleCommentCreateWithoutRaffleInput[] | Prisma.RaffleCommentUncheckedCreateWithoutRaffleInput[]
  connectOrCreate?: Prisma.RaffleCommentCreateOrConnectWithoutRaffleInput | Prisma.RaffleCommentCreateOrConnectWithoutRaffleInput[]
  createMany?: Prisma.RaffleCommentCreateManyRaffleInputEnvelope
  connect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
}

export type RaffleCommentUpdateManyWithoutRaffleNestedInput = {
  create?: Prisma.XOR<Prisma.RaffleCommentCreateWithoutRaffleInput, Prisma.RaffleCommentUncheckedCreateWithoutRaffleInput> | Prisma.RaffleCommentCreateWithoutRaffleInput[] | Prisma.RaffleCommentUncheckedCreateWithoutRaffleInput[]
  connectOrCreate?: Prisma.RaffleCommentCreateOrConnectWithoutRaffleInput | Prisma.RaffleCommentCreateOrConnectWithoutRaffleInput[]
  upsert?: Prisma.RaffleCommentUpsertWithWhereUniqueWithoutRaffleInput | Prisma.RaffleCommentUpsertWithWhereUniqueWithoutRaffleInput[]
  createMany?: Prisma.RaffleCommentCreateManyRaffleInputEnvelope
  set?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  disconnect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  delete?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  connect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  update?: Prisma.RaffleCommentUpdateWithWhereUniqueWithoutRaffleInput | Prisma.RaffleCommentUpdateWithWhereUniqueWithoutRaffleInput[]
  updateMany?: Prisma.RaffleCommentUpdateManyWithWhereWithoutRaffleInput | Prisma.RaffleCommentUpdateManyWithWhereWithoutRaffleInput[]
  deleteMany?: Prisma.RaffleCommentScalarWhereInput | Prisma.RaffleCommentScalarWhereInput[]
}

export type RaffleCommentUncheckedUpdateManyWithoutRaffleNestedInput = {
  create?: Prisma.XOR<Prisma.RaffleCommentCreateWithoutRaffleInput, Prisma.RaffleCommentUncheckedCreateWithoutRaffleInput> | Prisma.RaffleCommentCreateWithoutRaffleInput[] | Prisma.RaffleCommentUncheckedCreateWithoutRaffleInput[]
  connectOrCreate?: Prisma.RaffleCommentCreateOrConnectWithoutRaffleInput | Prisma.RaffleCommentCreateOrConnectWithoutRaffleInput[]
  upsert?: Prisma.RaffleCommentUpsertWithWhereUniqueWithoutRaffleInput | Prisma.RaffleCommentUpsertWithWhereUniqueWithoutRaffleInput[]
  createMany?: Prisma.RaffleCommentCreateManyRaffleInputEnvelope
  set?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  disconnect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  delete?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  connect?: Prisma.RaffleCommentWhereUniqueInput | Prisma.RaffleCommentWhereUniqueInput[]
  update?: Prisma.RaffleCommentUpdateWithWhereUniqueWithoutRaffleInput | Prisma.RaffleCommentUpdateWithWhereUniqueWithoutRaffleInput[]
  updateMany?: Prisma.RaffleCommentUpdateManyWithWhereWithoutRaffleInput | Prisma.RaffleCommentUpdateManyWithWhereWithoutRaffleInput[]
  deleteMany?: Prisma.RaffleCommentScalarWhereInput | Prisma.RaffleCommentScalarWhereInput[]
}

export type RaffleCommentCreateWithoutUserInput = {
  body: string
  createdAt?: Date | string
  raffle: Prisma.RaffleCreateNestedOneWithoutCommentsInput
}

export type RaffleCommentUncheckedCreateWithoutUserInput = {
  id?: number
  raffleId: number
  body: string
  createdAt?: Date | string
}

export type RaffleCommentCreateOrConnectWithoutUserInput = {
  where: Prisma.RaffleCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.RaffleCommentCreateWithoutUserInput, Prisma.RaffleCommentUncheckedCreateWithoutUserInput>
}

export type RaffleCommentCreateManyUserInputEnvelope = {
  data: Prisma.RaffleCommentCreateManyUserInput | Prisma.RaffleCommentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type RaffleCommentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.RaffleCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.RaffleCommentUpdateWithoutUserInput, Prisma.RaffleCommentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.RaffleCommentCreateWithoutUserInput, Prisma.RaffleCommentUncheckedCreateWithoutUserInput>
}

export type RaffleCommentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.RaffleCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.RaffleCommentUpdateWithoutUserInput, Prisma.RaffleCommentUncheckedUpdateWithoutUserInput>
}

export type RaffleCommentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.RaffleCommentScalarWhereInput
  data: Prisma.XOR<Prisma.RaffleCommentUpdateManyMutationInput, Prisma.RaffleCommentUncheckedUpdateManyWithoutUserInput>
}

export type RaffleCommentScalarWhereInput = {
  AND?: Prisma.RaffleCommentScalarWhereInput | Prisma.RaffleCommentScalarWhereInput[]
  OR?: Prisma.RaffleCommentScalarWhereInput[]
  NOT?: Prisma.RaffleCommentScalarWhereInput | Prisma.RaffleCommentScalarWhereInput[]
  id?: Prisma.IntFilter<"RaffleComment"> | number
  raffleId?: Prisma.IntFilter<"RaffleComment"> | number
  userId?: Prisma.IntFilter<"RaffleComment"> | number
  body?: Prisma.StringFilter<"RaffleComment"> | string
  createdAt?: Prisma.DateTimeFilter<"RaffleComment"> | Date | string
}

export type RaffleCommentCreateWithoutRaffleInput = {
  body: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutRaffleCommentsInput
}

export type RaffleCommentUncheckedCreateWithoutRaffleInput = {
  id?: number
  userId: number
  body: string
  createdAt?: Date | string
}

export type RaffleCommentCreateOrConnectWithoutRaffleInput = {
  where: Prisma.RaffleCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.RaffleCommentCreateWithoutRaffleInput, Prisma.RaffleCommentUncheckedCreateWithoutRaffleInput>
}

export type RaffleCommentCreateManyRaffleInputEnvelope = {
  data: Prisma.RaffleCommentCreateManyRaffleInput | Prisma.RaffleCommentCreateManyRaffleInput[]
  skipDuplicates?: boolean
}

export type RaffleCommentUpsertWithWhereUniqueWithoutRaffleInput = {
  where: Prisma.RaffleCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.RaffleCommentUpdateWithoutRaffleInput, Prisma.RaffleCommentUncheckedUpdateWithoutRaffleInput>
  create: Prisma.XOR<Prisma.RaffleCommentCreateWithoutRaffleInput, Prisma.RaffleCommentUncheckedCreateWithoutRaffleInput>
}

export type RaffleCommentUpdateWithWhereUniqueWithoutRaffleInput = {
  where: Prisma.RaffleCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.RaffleCommentUpdateWithoutRaffleInput, Prisma.RaffleCommentUncheckedUpdateWithoutRaffleInput>
}

export type RaffleCommentUpdateManyWithWhereWithoutRaffleInput = {
  where: Prisma.RaffleCommentScalarWhereInput
  data: Prisma.XOR<Prisma.RaffleCommentUpdateManyMutationInput, Prisma.RaffleCommentUncheckedUpdateManyWithoutRaffleInput>
}

export type RaffleCommentCreateManyUserInput = {
  id?: number
  raffleId: number
  body: string
  createdAt?: Date | string
}

export type RaffleCommentUpdateWithoutUserInput = {
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  raffle?: Prisma.RaffleUpdateOneRequiredWithoutCommentsNestedInput
}

export type RaffleCommentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  raffleId?: Prisma.IntFieldUpdateOperationsInput | number
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RaffleCommentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  raffleId?: Prisma.IntFieldUpdateOperationsInput | number
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RaffleCommentCreateManyRaffleInput = {
  id?: number
  userId: number
  body: string
  createdAt?: Date | string
}

export type RaffleCommentUpdateWithoutRaffleInput = {
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutRaffleCommentsNestedInput
}

export type RaffleCommentUncheckedUpdateWithoutRaffleInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RaffleCommentUncheckedUpdateManyWithoutRaffleInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RaffleCommentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  raffleId?: boolean
  userId?: boolean
  body?: boolean
  createdAt?: boolean
  raffle?: boolean | Prisma.RaffleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["raffleComment"]>

export type RaffleCommentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  raffleId?: boolean
  userId?: boolean
  body?: boolean
  createdAt?: boolean
  raffle?: boolean | Prisma.RaffleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["raffleComment"]>

export type RaffleCommentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  raffleId?: boolean
  userId?: boolean
  body?: boolean
  createdAt?: boolean
  raffle?: boolean | Prisma.RaffleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["raffleComment"]>

export type RaffleCommentSelectScalar = {
  id?: boolean
  raffleId?: boolean
  userId?: boolean
  body?: boolean
  createdAt?: boolean
}

export type RaffleCommentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "raffleId" | "userId" | "body" | "createdAt", ExtArgs["result"]["raffleComment"]>
export type RaffleCommentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  raffle?: boolean | Prisma.RaffleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type RaffleCommentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  raffle?: boolean | Prisma.RaffleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type RaffleCommentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  raffle?: boolean | Prisma.RaffleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $RaffleCommentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RaffleComment"
  objects: {
    raffle: Prisma.$RafflePayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    raffleId: number
    userId: number
    body: string
    createdAt: Date
  }, ExtArgs["result"]["raffleComment"]>
  composites: {}
}

export type RaffleCommentGetPayload<S extends boolean | null | undefined | RaffleCommentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload, S>

export type RaffleCommentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RaffleCommentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RaffleCommentCountAggregateInputType | true
  }

export interface RaffleCommentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RaffleComment'], meta: { name: 'RaffleComment' } }
  /**
   * Find zero or one RaffleComment that matches the filter.
   * @param {RaffleCommentFindUniqueArgs} args - Arguments to find a RaffleComment
   * @example
   * // Get one RaffleComment
   * const raffleComment = await prisma.raffleComment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RaffleCommentFindUniqueArgs>(args: Prisma.SelectSubset<T, RaffleCommentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RaffleCommentClient<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RaffleComment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RaffleCommentFindUniqueOrThrowArgs} args - Arguments to find a RaffleComment
   * @example
   * // Get one RaffleComment
   * const raffleComment = await prisma.raffleComment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RaffleCommentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RaffleCommentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RaffleCommentClient<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RaffleComment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaffleCommentFindFirstArgs} args - Arguments to find a RaffleComment
   * @example
   * // Get one RaffleComment
   * const raffleComment = await prisma.raffleComment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RaffleCommentFindFirstArgs>(args?: Prisma.SelectSubset<T, RaffleCommentFindFirstArgs<ExtArgs>>): Prisma.Prisma__RaffleCommentClient<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RaffleComment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaffleCommentFindFirstOrThrowArgs} args - Arguments to find a RaffleComment
   * @example
   * // Get one RaffleComment
   * const raffleComment = await prisma.raffleComment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RaffleCommentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RaffleCommentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RaffleCommentClient<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RaffleComments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaffleCommentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RaffleComments
   * const raffleComments = await prisma.raffleComment.findMany()
   * 
   * // Get first 10 RaffleComments
   * const raffleComments = await prisma.raffleComment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const raffleCommentWithIdOnly = await prisma.raffleComment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RaffleCommentFindManyArgs>(args?: Prisma.SelectSubset<T, RaffleCommentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RaffleComment.
   * @param {RaffleCommentCreateArgs} args - Arguments to create a RaffleComment.
   * @example
   * // Create one RaffleComment
   * const RaffleComment = await prisma.raffleComment.create({
   *   data: {
   *     // ... data to create a RaffleComment
   *   }
   * })
   * 
   */
  create<T extends RaffleCommentCreateArgs>(args: Prisma.SelectSubset<T, RaffleCommentCreateArgs<ExtArgs>>): Prisma.Prisma__RaffleCommentClient<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RaffleComments.
   * @param {RaffleCommentCreateManyArgs} args - Arguments to create many RaffleComments.
   * @example
   * // Create many RaffleComments
   * const raffleComment = await prisma.raffleComment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RaffleCommentCreateManyArgs>(args?: Prisma.SelectSubset<T, RaffleCommentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RaffleComments and returns the data saved in the database.
   * @param {RaffleCommentCreateManyAndReturnArgs} args - Arguments to create many RaffleComments.
   * @example
   * // Create many RaffleComments
   * const raffleComment = await prisma.raffleComment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RaffleComments and only return the `id`
   * const raffleCommentWithIdOnly = await prisma.raffleComment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RaffleCommentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RaffleCommentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RaffleComment.
   * @param {RaffleCommentDeleteArgs} args - Arguments to delete one RaffleComment.
   * @example
   * // Delete one RaffleComment
   * const RaffleComment = await prisma.raffleComment.delete({
   *   where: {
   *     // ... filter to delete one RaffleComment
   *   }
   * })
   * 
   */
  delete<T extends RaffleCommentDeleteArgs>(args: Prisma.SelectSubset<T, RaffleCommentDeleteArgs<ExtArgs>>): Prisma.Prisma__RaffleCommentClient<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RaffleComment.
   * @param {RaffleCommentUpdateArgs} args - Arguments to update one RaffleComment.
   * @example
   * // Update one RaffleComment
   * const raffleComment = await prisma.raffleComment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RaffleCommentUpdateArgs>(args: Prisma.SelectSubset<T, RaffleCommentUpdateArgs<ExtArgs>>): Prisma.Prisma__RaffleCommentClient<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RaffleComments.
   * @param {RaffleCommentDeleteManyArgs} args - Arguments to filter RaffleComments to delete.
   * @example
   * // Delete a few RaffleComments
   * const { count } = await prisma.raffleComment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RaffleCommentDeleteManyArgs>(args?: Prisma.SelectSubset<T, RaffleCommentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RaffleComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaffleCommentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RaffleComments
   * const raffleComment = await prisma.raffleComment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RaffleCommentUpdateManyArgs>(args: Prisma.SelectSubset<T, RaffleCommentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RaffleComments and returns the data updated in the database.
   * @param {RaffleCommentUpdateManyAndReturnArgs} args - Arguments to update many RaffleComments.
   * @example
   * // Update many RaffleComments
   * const raffleComment = await prisma.raffleComment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RaffleComments and only return the `id`
   * const raffleCommentWithIdOnly = await prisma.raffleComment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RaffleCommentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RaffleCommentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RaffleComment.
   * @param {RaffleCommentUpsertArgs} args - Arguments to update or create a RaffleComment.
   * @example
   * // Update or create a RaffleComment
   * const raffleComment = await prisma.raffleComment.upsert({
   *   create: {
   *     // ... data to create a RaffleComment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RaffleComment we want to update
   *   }
   * })
   */
  upsert<T extends RaffleCommentUpsertArgs>(args: Prisma.SelectSubset<T, RaffleCommentUpsertArgs<ExtArgs>>): Prisma.Prisma__RaffleCommentClient<runtime.Types.Result.GetResult<Prisma.$RaffleCommentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RaffleComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaffleCommentCountArgs} args - Arguments to filter RaffleComments to count.
   * @example
   * // Count the number of RaffleComments
   * const count = await prisma.raffleComment.count({
   *   where: {
   *     // ... the filter for the RaffleComments we want to count
   *   }
   * })
  **/
  count<T extends RaffleCommentCountArgs>(
    args?: Prisma.Subset<T, RaffleCommentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RaffleCommentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RaffleComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaffleCommentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RaffleCommentAggregateArgs>(args: Prisma.Subset<T, RaffleCommentAggregateArgs>): Prisma.PrismaPromise<GetRaffleCommentAggregateType<T>>

  /**
   * Group by RaffleComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaffleCommentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RaffleCommentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RaffleCommentGroupByArgs['orderBy'] }
      : { orderBy?: RaffleCommentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RaffleCommentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRaffleCommentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RaffleComment model
 */
readonly fields: RaffleCommentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RaffleComment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RaffleCommentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  raffle<T extends Prisma.RaffleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RaffleDefaultArgs<ExtArgs>>): Prisma.Prisma__RaffleClient<runtime.Types.Result.GetResult<Prisma.$RafflePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RaffleComment model
 */
export interface RaffleCommentFieldRefs {
  readonly id: Prisma.FieldRef<"RaffleComment", 'Int'>
  readonly raffleId: Prisma.FieldRef<"RaffleComment", 'Int'>
  readonly userId: Prisma.FieldRef<"RaffleComment", 'Int'>
  readonly body: Prisma.FieldRef<"RaffleComment", 'String'>
  readonly createdAt: Prisma.FieldRef<"RaffleComment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RaffleComment findUnique
 */
export type RaffleCommentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentInclude<ExtArgs> | null
  /**
   * Filter, which RaffleComment to fetch.
   */
  where: Prisma.RaffleCommentWhereUniqueInput
}

/**
 * RaffleComment findUniqueOrThrow
 */
export type RaffleCommentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentInclude<ExtArgs> | null
  /**
   * Filter, which RaffleComment to fetch.
   */
  where: Prisma.RaffleCommentWhereUniqueInput
}

/**
 * RaffleComment findFirst
 */
export type RaffleCommentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentInclude<ExtArgs> | null
  /**
   * Filter, which RaffleComment to fetch.
   */
  where?: Prisma.RaffleCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RaffleComments to fetch.
   */
  orderBy?: Prisma.RaffleCommentOrderByWithRelationInput | Prisma.RaffleCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RaffleComments.
   */
  cursor?: Prisma.RaffleCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RaffleComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RaffleComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RaffleComments.
   */
  distinct?: Prisma.RaffleCommentScalarFieldEnum | Prisma.RaffleCommentScalarFieldEnum[]
}

/**
 * RaffleComment findFirstOrThrow
 */
export type RaffleCommentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentInclude<ExtArgs> | null
  /**
   * Filter, which RaffleComment to fetch.
   */
  where?: Prisma.RaffleCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RaffleComments to fetch.
   */
  orderBy?: Prisma.RaffleCommentOrderByWithRelationInput | Prisma.RaffleCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RaffleComments.
   */
  cursor?: Prisma.RaffleCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RaffleComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RaffleComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RaffleComments.
   */
  distinct?: Prisma.RaffleCommentScalarFieldEnum | Prisma.RaffleCommentScalarFieldEnum[]
}

/**
 * RaffleComment findMany
 */
export type RaffleCommentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentInclude<ExtArgs> | null
  /**
   * Filter, which RaffleComments to fetch.
   */
  where?: Prisma.RaffleCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RaffleComments to fetch.
   */
  orderBy?: Prisma.RaffleCommentOrderByWithRelationInput | Prisma.RaffleCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RaffleComments.
   */
  cursor?: Prisma.RaffleCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RaffleComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RaffleComments.
   */
  skip?: number
  distinct?: Prisma.RaffleCommentScalarFieldEnum | Prisma.RaffleCommentScalarFieldEnum[]
}

/**
 * RaffleComment create
 */
export type RaffleCommentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentInclude<ExtArgs> | null
  /**
   * The data needed to create a RaffleComment.
   */
  data: Prisma.XOR<Prisma.RaffleCommentCreateInput, Prisma.RaffleCommentUncheckedCreateInput>
}

/**
 * RaffleComment createMany
 */
export type RaffleCommentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RaffleComments.
   */
  data: Prisma.RaffleCommentCreateManyInput | Prisma.RaffleCommentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RaffleComment createManyAndReturn
 */
export type RaffleCommentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * The data used to create many RaffleComments.
   */
  data: Prisma.RaffleCommentCreateManyInput | Prisma.RaffleCommentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RaffleComment update
 */
export type RaffleCommentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentInclude<ExtArgs> | null
  /**
   * The data needed to update a RaffleComment.
   */
  data: Prisma.XOR<Prisma.RaffleCommentUpdateInput, Prisma.RaffleCommentUncheckedUpdateInput>
  /**
   * Choose, which RaffleComment to update.
   */
  where: Prisma.RaffleCommentWhereUniqueInput
}

/**
 * RaffleComment updateMany
 */
export type RaffleCommentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RaffleComments.
   */
  data: Prisma.XOR<Prisma.RaffleCommentUpdateManyMutationInput, Prisma.RaffleCommentUncheckedUpdateManyInput>
  /**
   * Filter which RaffleComments to update
   */
  where?: Prisma.RaffleCommentWhereInput
  /**
   * Limit how many RaffleComments to update.
   */
  limit?: number
}

/**
 * RaffleComment updateManyAndReturn
 */
export type RaffleCommentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * The data used to update RaffleComments.
   */
  data: Prisma.XOR<Prisma.RaffleCommentUpdateManyMutationInput, Prisma.RaffleCommentUncheckedUpdateManyInput>
  /**
   * Filter which RaffleComments to update
   */
  where?: Prisma.RaffleCommentWhereInput
  /**
   * Limit how many RaffleComments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RaffleComment upsert
 */
export type RaffleCommentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentInclude<ExtArgs> | null
  /**
   * The filter to search for the RaffleComment to update in case it exists.
   */
  where: Prisma.RaffleCommentWhereUniqueInput
  /**
   * In case the RaffleComment found by the `where` argument doesn't exist, create a new RaffleComment with this data.
   */
  create: Prisma.XOR<Prisma.RaffleCommentCreateInput, Prisma.RaffleCommentUncheckedCreateInput>
  /**
   * In case the RaffleComment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RaffleCommentUpdateInput, Prisma.RaffleCommentUncheckedUpdateInput>
}

/**
 * RaffleComment delete
 */
export type RaffleCommentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentInclude<ExtArgs> | null
  /**
   * Filter which RaffleComment to delete.
   */
  where: Prisma.RaffleCommentWhereUniqueInput
}

/**
 * RaffleComment deleteMany
 */
export type RaffleCommentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RaffleComments to delete
   */
  where?: Prisma.RaffleCommentWhereInput
  /**
   * Limit how many RaffleComments to delete.
   */
  limit?: number
}

/**
 * RaffleComment without action
 */
export type RaffleCommentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaffleComment
   */
  select?: Prisma.RaffleCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaffleComment
   */
  omit?: Prisma.RaffleCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaffleCommentInclude<ExtArgs> | null
}
