
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UnsubscribeToken` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UnsubscribeToken
 * 
 */
export type UnsubscribeTokenModel = runtime.Types.Result.DefaultSelection<Prisma.$UnsubscribeTokenPayload>

export type AggregateUnsubscribeToken = {
  _count: UnsubscribeTokenCountAggregateOutputType | null
  _avg: UnsubscribeTokenAvgAggregateOutputType | null
  _sum: UnsubscribeTokenSumAggregateOutputType | null
  _min: UnsubscribeTokenMinAggregateOutputType | null
  _max: UnsubscribeTokenMaxAggregateOutputType | null
}

export type UnsubscribeTokenAvgAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type UnsubscribeTokenSumAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type UnsubscribeTokenMinAggregateOutputType = {
  id: number | null
  userId: number | null
  token: string | null
  createdAt: Date | null
}

export type UnsubscribeTokenMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  token: string | null
  createdAt: Date | null
}

export type UnsubscribeTokenCountAggregateOutputType = {
  id: number
  userId: number
  token: number
  createdAt: number
  _all: number
}


export type UnsubscribeTokenAvgAggregateInputType = {
  id?: true
  userId?: true
}

export type UnsubscribeTokenSumAggregateInputType = {
  id?: true
  userId?: true
}

export type UnsubscribeTokenMinAggregateInputType = {
  id?: true
  userId?: true
  token?: true
  createdAt?: true
}

export type UnsubscribeTokenMaxAggregateInputType = {
  id?: true
  userId?: true
  token?: true
  createdAt?: true
}

export type UnsubscribeTokenCountAggregateInputType = {
  id?: true
  userId?: true
  token?: true
  createdAt?: true
  _all?: true
}

export type UnsubscribeTokenAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UnsubscribeToken to aggregate.
   */
  where?: Prisma.UnsubscribeTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnsubscribeTokens to fetch.
   */
  orderBy?: Prisma.UnsubscribeTokenOrderByWithRelationInput | Prisma.UnsubscribeTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UnsubscribeTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnsubscribeTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnsubscribeTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UnsubscribeTokens
  **/
  _count?: true | UnsubscribeTokenCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UnsubscribeTokenAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UnsubscribeTokenSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UnsubscribeTokenMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UnsubscribeTokenMaxAggregateInputType
}

export type GetUnsubscribeTokenAggregateType<T extends UnsubscribeTokenAggregateArgs> = {
      [P in keyof T & keyof AggregateUnsubscribeToken]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUnsubscribeToken[P]>
    : Prisma.GetScalarType<T[P], AggregateUnsubscribeToken[P]>
}




export type UnsubscribeTokenGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnsubscribeTokenWhereInput
  orderBy?: Prisma.UnsubscribeTokenOrderByWithAggregationInput | Prisma.UnsubscribeTokenOrderByWithAggregationInput[]
  by: Prisma.UnsubscribeTokenScalarFieldEnum[] | Prisma.UnsubscribeTokenScalarFieldEnum
  having?: Prisma.UnsubscribeTokenScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UnsubscribeTokenCountAggregateInputType | true
  _avg?: UnsubscribeTokenAvgAggregateInputType
  _sum?: UnsubscribeTokenSumAggregateInputType
  _min?: UnsubscribeTokenMinAggregateInputType
  _max?: UnsubscribeTokenMaxAggregateInputType
}

export type UnsubscribeTokenGroupByOutputType = {
  id: number
  userId: number
  token: string
  createdAt: Date
  _count: UnsubscribeTokenCountAggregateOutputType | null
  _avg: UnsubscribeTokenAvgAggregateOutputType | null
  _sum: UnsubscribeTokenSumAggregateOutputType | null
  _min: UnsubscribeTokenMinAggregateOutputType | null
  _max: UnsubscribeTokenMaxAggregateOutputType | null
}

type GetUnsubscribeTokenGroupByPayload<T extends UnsubscribeTokenGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UnsubscribeTokenGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UnsubscribeTokenGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UnsubscribeTokenGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UnsubscribeTokenGroupByOutputType[P]>
      }
    >
  >



export type UnsubscribeTokenWhereInput = {
  AND?: Prisma.UnsubscribeTokenWhereInput | Prisma.UnsubscribeTokenWhereInput[]
  OR?: Prisma.UnsubscribeTokenWhereInput[]
  NOT?: Prisma.UnsubscribeTokenWhereInput | Prisma.UnsubscribeTokenWhereInput[]
  id?: Prisma.IntFilter<"UnsubscribeToken"> | number
  userId?: Prisma.IntFilter<"UnsubscribeToken"> | number
  token?: Prisma.StringFilter<"UnsubscribeToken"> | string
  createdAt?: Prisma.DateTimeFilter<"UnsubscribeToken"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UnsubscribeTokenOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  token?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UnsubscribeTokenWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  token?: string
  AND?: Prisma.UnsubscribeTokenWhereInput | Prisma.UnsubscribeTokenWhereInput[]
  OR?: Prisma.UnsubscribeTokenWhereInput[]
  NOT?: Prisma.UnsubscribeTokenWhereInput | Prisma.UnsubscribeTokenWhereInput[]
  userId?: Prisma.IntFilter<"UnsubscribeToken"> | number
  createdAt?: Prisma.DateTimeFilter<"UnsubscribeToken"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "token">

export type UnsubscribeTokenOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  token?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.UnsubscribeTokenCountOrderByAggregateInput
  _avg?: Prisma.UnsubscribeTokenAvgOrderByAggregateInput
  _max?: Prisma.UnsubscribeTokenMaxOrderByAggregateInput
  _min?: Prisma.UnsubscribeTokenMinOrderByAggregateInput
  _sum?: Prisma.UnsubscribeTokenSumOrderByAggregateInput
}

export type UnsubscribeTokenScalarWhereWithAggregatesInput = {
  AND?: Prisma.UnsubscribeTokenScalarWhereWithAggregatesInput | Prisma.UnsubscribeTokenScalarWhereWithAggregatesInput[]
  OR?: Prisma.UnsubscribeTokenScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UnsubscribeTokenScalarWhereWithAggregatesInput | Prisma.UnsubscribeTokenScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"UnsubscribeToken"> | number
  userId?: Prisma.IntWithAggregatesFilter<"UnsubscribeToken"> | number
  token?: Prisma.StringWithAggregatesFilter<"UnsubscribeToken"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UnsubscribeToken"> | Date | string
}

export type UnsubscribeTokenCreateInput = {
  token: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUnsubscribeTokensInput
}

export type UnsubscribeTokenUncheckedCreateInput = {
  id?: number
  userId: number
  token: string
  createdAt?: Date | string
}

export type UnsubscribeTokenUpdateInput = {
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUnsubscribeTokensNestedInput
}

export type UnsubscribeTokenUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnsubscribeTokenCreateManyInput = {
  id?: number
  userId: number
  token: string
  createdAt?: Date | string
}

export type UnsubscribeTokenUpdateManyMutationInput = {
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnsubscribeTokenUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnsubscribeTokenListRelationFilter = {
  every?: Prisma.UnsubscribeTokenWhereInput
  some?: Prisma.UnsubscribeTokenWhereInput
  none?: Prisma.UnsubscribeTokenWhereInput
}

export type UnsubscribeTokenOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UnsubscribeTokenCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  token?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UnsubscribeTokenAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type UnsubscribeTokenMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  token?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UnsubscribeTokenMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  token?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UnsubscribeTokenSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type UnsubscribeTokenCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UnsubscribeTokenCreateWithoutUserInput, Prisma.UnsubscribeTokenUncheckedCreateWithoutUserInput> | Prisma.UnsubscribeTokenCreateWithoutUserInput[] | Prisma.UnsubscribeTokenUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UnsubscribeTokenCreateOrConnectWithoutUserInput | Prisma.UnsubscribeTokenCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UnsubscribeTokenCreateManyUserInputEnvelope
  connect?: Prisma.UnsubscribeTokenWhereUniqueInput | Prisma.UnsubscribeTokenWhereUniqueInput[]
}

export type UnsubscribeTokenUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UnsubscribeTokenCreateWithoutUserInput, Prisma.UnsubscribeTokenUncheckedCreateWithoutUserInput> | Prisma.UnsubscribeTokenCreateWithoutUserInput[] | Prisma.UnsubscribeTokenUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UnsubscribeTokenCreateOrConnectWithoutUserInput | Prisma.UnsubscribeTokenCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UnsubscribeTokenCreateManyUserInputEnvelope
  connect?: Prisma.UnsubscribeTokenWhereUniqueInput | Prisma.UnsubscribeTokenWhereUniqueInput[]
}

export type UnsubscribeTokenUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UnsubscribeTokenCreateWithoutUserInput, Prisma.UnsubscribeTokenUncheckedCreateWithoutUserInput> | Prisma.UnsubscribeTokenCreateWithoutUserInput[] | Prisma.UnsubscribeTokenUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UnsubscribeTokenCreateOrConnectWithoutUserInput | Prisma.UnsubscribeTokenCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UnsubscribeTokenUpsertWithWhereUniqueWithoutUserInput | Prisma.UnsubscribeTokenUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UnsubscribeTokenCreateManyUserInputEnvelope
  set?: Prisma.UnsubscribeTokenWhereUniqueInput | Prisma.UnsubscribeTokenWhereUniqueInput[]
  disconnect?: Prisma.UnsubscribeTokenWhereUniqueInput | Prisma.UnsubscribeTokenWhereUniqueInput[]
  delete?: Prisma.UnsubscribeTokenWhereUniqueInput | Prisma.UnsubscribeTokenWhereUniqueInput[]
  connect?: Prisma.UnsubscribeTokenWhereUniqueInput | Prisma.UnsubscribeTokenWhereUniqueInput[]
  update?: Prisma.UnsubscribeTokenUpdateWithWhereUniqueWithoutUserInput | Prisma.UnsubscribeTokenUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UnsubscribeTokenUpdateManyWithWhereWithoutUserInput | Prisma.UnsubscribeTokenUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UnsubscribeTokenScalarWhereInput | Prisma.UnsubscribeTokenScalarWhereInput[]
}

export type UnsubscribeTokenUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UnsubscribeTokenCreateWithoutUserInput, Prisma.UnsubscribeTokenUncheckedCreateWithoutUserInput> | Prisma.UnsubscribeTokenCreateWithoutUserInput[] | Prisma.UnsubscribeTokenUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UnsubscribeTokenCreateOrConnectWithoutUserInput | Prisma.UnsubscribeTokenCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UnsubscribeTokenUpsertWithWhereUniqueWithoutUserInput | Prisma.UnsubscribeTokenUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UnsubscribeTokenCreateManyUserInputEnvelope
  set?: Prisma.UnsubscribeTokenWhereUniqueInput | Prisma.UnsubscribeTokenWhereUniqueInput[]
  disconnect?: Prisma.UnsubscribeTokenWhereUniqueInput | Prisma.UnsubscribeTokenWhereUniqueInput[]
  delete?: Prisma.UnsubscribeTokenWhereUniqueInput | Prisma.UnsubscribeTokenWhereUniqueInput[]
  connect?: Prisma.UnsubscribeTokenWhereUniqueInput | Prisma.UnsubscribeTokenWhereUniqueInput[]
  update?: Prisma.UnsubscribeTokenUpdateWithWhereUniqueWithoutUserInput | Prisma.UnsubscribeTokenUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UnsubscribeTokenUpdateManyWithWhereWithoutUserInput | Prisma.UnsubscribeTokenUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UnsubscribeTokenScalarWhereInput | Prisma.UnsubscribeTokenScalarWhereInput[]
}

export type UnsubscribeTokenCreateWithoutUserInput = {
  token: string
  createdAt?: Date | string
}

export type UnsubscribeTokenUncheckedCreateWithoutUserInput = {
  id?: number
  token: string
  createdAt?: Date | string
}

export type UnsubscribeTokenCreateOrConnectWithoutUserInput = {
  where: Prisma.UnsubscribeTokenWhereUniqueInput
  create: Prisma.XOR<Prisma.UnsubscribeTokenCreateWithoutUserInput, Prisma.UnsubscribeTokenUncheckedCreateWithoutUserInput>
}

export type UnsubscribeTokenCreateManyUserInputEnvelope = {
  data: Prisma.UnsubscribeTokenCreateManyUserInput | Prisma.UnsubscribeTokenCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UnsubscribeTokenUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UnsubscribeTokenWhereUniqueInput
  update: Prisma.XOR<Prisma.UnsubscribeTokenUpdateWithoutUserInput, Prisma.UnsubscribeTokenUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UnsubscribeTokenCreateWithoutUserInput, Prisma.UnsubscribeTokenUncheckedCreateWithoutUserInput>
}

export type UnsubscribeTokenUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UnsubscribeTokenWhereUniqueInput
  data: Prisma.XOR<Prisma.UnsubscribeTokenUpdateWithoutUserInput, Prisma.UnsubscribeTokenUncheckedUpdateWithoutUserInput>
}

export type UnsubscribeTokenUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UnsubscribeTokenScalarWhereInput
  data: Prisma.XOR<Prisma.UnsubscribeTokenUpdateManyMutationInput, Prisma.UnsubscribeTokenUncheckedUpdateManyWithoutUserInput>
}

export type UnsubscribeTokenScalarWhereInput = {
  AND?: Prisma.UnsubscribeTokenScalarWhereInput | Prisma.UnsubscribeTokenScalarWhereInput[]
  OR?: Prisma.UnsubscribeTokenScalarWhereInput[]
  NOT?: Prisma.UnsubscribeTokenScalarWhereInput | Prisma.UnsubscribeTokenScalarWhereInput[]
  id?: Prisma.IntFilter<"UnsubscribeToken"> | number
  userId?: Prisma.IntFilter<"UnsubscribeToken"> | number
  token?: Prisma.StringFilter<"UnsubscribeToken"> | string
  createdAt?: Prisma.DateTimeFilter<"UnsubscribeToken"> | Date | string
}

export type UnsubscribeTokenCreateManyUserInput = {
  id?: number
  token: string
  createdAt?: Date | string
}

export type UnsubscribeTokenUpdateWithoutUserInput = {
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnsubscribeTokenUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnsubscribeTokenUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  token?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UnsubscribeTokenSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  token?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unsubscribeToken"]>

export type UnsubscribeTokenSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  token?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unsubscribeToken"]>

export type UnsubscribeTokenSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  token?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unsubscribeToken"]>

export type UnsubscribeTokenSelectScalar = {
  id?: boolean
  userId?: boolean
  token?: boolean
  createdAt?: boolean
}

export type UnsubscribeTokenOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "token" | "createdAt", ExtArgs["result"]["unsubscribeToken"]>
export type UnsubscribeTokenInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UnsubscribeTokenIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UnsubscribeTokenIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UnsubscribeTokenPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UnsubscribeToken"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    token: string
    createdAt: Date
  }, ExtArgs["result"]["unsubscribeToken"]>
  composites: {}
}

export type UnsubscribeTokenGetPayload<S extends boolean | null | undefined | UnsubscribeTokenDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload, S>

export type UnsubscribeTokenCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UnsubscribeTokenFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UnsubscribeTokenCountAggregateInputType | true
  }

export interface UnsubscribeTokenDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UnsubscribeToken'], meta: { name: 'UnsubscribeToken' } }
  /**
   * Find zero or one UnsubscribeToken that matches the filter.
   * @param {UnsubscribeTokenFindUniqueArgs} args - Arguments to find a UnsubscribeToken
   * @example
   * // Get one UnsubscribeToken
   * const unsubscribeToken = await prisma.unsubscribeToken.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UnsubscribeTokenFindUniqueArgs>(args: Prisma.SelectSubset<T, UnsubscribeTokenFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UnsubscribeTokenClient<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UnsubscribeToken that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UnsubscribeTokenFindUniqueOrThrowArgs} args - Arguments to find a UnsubscribeToken
   * @example
   * // Get one UnsubscribeToken
   * const unsubscribeToken = await prisma.unsubscribeToken.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UnsubscribeTokenFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UnsubscribeTokenFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnsubscribeTokenClient<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UnsubscribeToken that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnsubscribeTokenFindFirstArgs} args - Arguments to find a UnsubscribeToken
   * @example
   * // Get one UnsubscribeToken
   * const unsubscribeToken = await prisma.unsubscribeToken.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UnsubscribeTokenFindFirstArgs>(args?: Prisma.SelectSubset<T, UnsubscribeTokenFindFirstArgs<ExtArgs>>): Prisma.Prisma__UnsubscribeTokenClient<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UnsubscribeToken that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnsubscribeTokenFindFirstOrThrowArgs} args - Arguments to find a UnsubscribeToken
   * @example
   * // Get one UnsubscribeToken
   * const unsubscribeToken = await prisma.unsubscribeToken.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UnsubscribeTokenFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UnsubscribeTokenFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnsubscribeTokenClient<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UnsubscribeTokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnsubscribeTokenFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UnsubscribeTokens
   * const unsubscribeTokens = await prisma.unsubscribeToken.findMany()
   * 
   * // Get first 10 UnsubscribeTokens
   * const unsubscribeTokens = await prisma.unsubscribeToken.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const unsubscribeTokenWithIdOnly = await prisma.unsubscribeToken.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UnsubscribeTokenFindManyArgs>(args?: Prisma.SelectSubset<T, UnsubscribeTokenFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UnsubscribeToken.
   * @param {UnsubscribeTokenCreateArgs} args - Arguments to create a UnsubscribeToken.
   * @example
   * // Create one UnsubscribeToken
   * const UnsubscribeToken = await prisma.unsubscribeToken.create({
   *   data: {
   *     // ... data to create a UnsubscribeToken
   *   }
   * })
   * 
   */
  create<T extends UnsubscribeTokenCreateArgs>(args: Prisma.SelectSubset<T, UnsubscribeTokenCreateArgs<ExtArgs>>): Prisma.Prisma__UnsubscribeTokenClient<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UnsubscribeTokens.
   * @param {UnsubscribeTokenCreateManyArgs} args - Arguments to create many UnsubscribeTokens.
   * @example
   * // Create many UnsubscribeTokens
   * const unsubscribeToken = await prisma.unsubscribeToken.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UnsubscribeTokenCreateManyArgs>(args?: Prisma.SelectSubset<T, UnsubscribeTokenCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UnsubscribeTokens and returns the data saved in the database.
   * @param {UnsubscribeTokenCreateManyAndReturnArgs} args - Arguments to create many UnsubscribeTokens.
   * @example
   * // Create many UnsubscribeTokens
   * const unsubscribeToken = await prisma.unsubscribeToken.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UnsubscribeTokens and only return the `id`
   * const unsubscribeTokenWithIdOnly = await prisma.unsubscribeToken.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UnsubscribeTokenCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UnsubscribeTokenCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UnsubscribeToken.
   * @param {UnsubscribeTokenDeleteArgs} args - Arguments to delete one UnsubscribeToken.
   * @example
   * // Delete one UnsubscribeToken
   * const UnsubscribeToken = await prisma.unsubscribeToken.delete({
   *   where: {
   *     // ... filter to delete one UnsubscribeToken
   *   }
   * })
   * 
   */
  delete<T extends UnsubscribeTokenDeleteArgs>(args: Prisma.SelectSubset<T, UnsubscribeTokenDeleteArgs<ExtArgs>>): Prisma.Prisma__UnsubscribeTokenClient<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UnsubscribeToken.
   * @param {UnsubscribeTokenUpdateArgs} args - Arguments to update one UnsubscribeToken.
   * @example
   * // Update one UnsubscribeToken
   * const unsubscribeToken = await prisma.unsubscribeToken.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UnsubscribeTokenUpdateArgs>(args: Prisma.SelectSubset<T, UnsubscribeTokenUpdateArgs<ExtArgs>>): Prisma.Prisma__UnsubscribeTokenClient<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UnsubscribeTokens.
   * @param {UnsubscribeTokenDeleteManyArgs} args - Arguments to filter UnsubscribeTokens to delete.
   * @example
   * // Delete a few UnsubscribeTokens
   * const { count } = await prisma.unsubscribeToken.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UnsubscribeTokenDeleteManyArgs>(args?: Prisma.SelectSubset<T, UnsubscribeTokenDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UnsubscribeTokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnsubscribeTokenUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UnsubscribeTokens
   * const unsubscribeToken = await prisma.unsubscribeToken.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UnsubscribeTokenUpdateManyArgs>(args: Prisma.SelectSubset<T, UnsubscribeTokenUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UnsubscribeTokens and returns the data updated in the database.
   * @param {UnsubscribeTokenUpdateManyAndReturnArgs} args - Arguments to update many UnsubscribeTokens.
   * @example
   * // Update many UnsubscribeTokens
   * const unsubscribeToken = await prisma.unsubscribeToken.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UnsubscribeTokens and only return the `id`
   * const unsubscribeTokenWithIdOnly = await prisma.unsubscribeToken.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UnsubscribeTokenUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UnsubscribeTokenUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UnsubscribeToken.
   * @param {UnsubscribeTokenUpsertArgs} args - Arguments to update or create a UnsubscribeToken.
   * @example
   * // Update or create a UnsubscribeToken
   * const unsubscribeToken = await prisma.unsubscribeToken.upsert({
   *   create: {
   *     // ... data to create a UnsubscribeToken
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UnsubscribeToken we want to update
   *   }
   * })
   */
  upsert<T extends UnsubscribeTokenUpsertArgs>(args: Prisma.SelectSubset<T, UnsubscribeTokenUpsertArgs<ExtArgs>>): Prisma.Prisma__UnsubscribeTokenClient<runtime.Types.Result.GetResult<Prisma.$UnsubscribeTokenPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UnsubscribeTokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnsubscribeTokenCountArgs} args - Arguments to filter UnsubscribeTokens to count.
   * @example
   * // Count the number of UnsubscribeTokens
   * const count = await prisma.unsubscribeToken.count({
   *   where: {
   *     // ... the filter for the UnsubscribeTokens we want to count
   *   }
   * })
  **/
  count<T extends UnsubscribeTokenCountArgs>(
    args?: Prisma.Subset<T, UnsubscribeTokenCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UnsubscribeTokenCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UnsubscribeToken.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnsubscribeTokenAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UnsubscribeTokenAggregateArgs>(args: Prisma.Subset<T, UnsubscribeTokenAggregateArgs>): Prisma.PrismaPromise<GetUnsubscribeTokenAggregateType<T>>

  /**
   * Group by UnsubscribeToken.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnsubscribeTokenGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UnsubscribeTokenGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UnsubscribeTokenGroupByArgs['orderBy'] }
      : { orderBy?: UnsubscribeTokenGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UnsubscribeTokenGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUnsubscribeTokenGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UnsubscribeToken model
 */
readonly fields: UnsubscribeTokenFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UnsubscribeToken.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UnsubscribeTokenClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UnsubscribeToken model
 */
export interface UnsubscribeTokenFieldRefs {
  readonly id: Prisma.FieldRef<"UnsubscribeToken", 'Int'>
  readonly userId: Prisma.FieldRef<"UnsubscribeToken", 'Int'>
  readonly token: Prisma.FieldRef<"UnsubscribeToken", 'String'>
  readonly createdAt: Prisma.FieldRef<"UnsubscribeToken", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UnsubscribeToken findUnique
 */
export type UnsubscribeTokenFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenInclude<ExtArgs> | null
  /**
   * Filter, which UnsubscribeToken to fetch.
   */
  where: Prisma.UnsubscribeTokenWhereUniqueInput
}

/**
 * UnsubscribeToken findUniqueOrThrow
 */
export type UnsubscribeTokenFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenInclude<ExtArgs> | null
  /**
   * Filter, which UnsubscribeToken to fetch.
   */
  where: Prisma.UnsubscribeTokenWhereUniqueInput
}

/**
 * UnsubscribeToken findFirst
 */
export type UnsubscribeTokenFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenInclude<ExtArgs> | null
  /**
   * Filter, which UnsubscribeToken to fetch.
   */
  where?: Prisma.UnsubscribeTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnsubscribeTokens to fetch.
   */
  orderBy?: Prisma.UnsubscribeTokenOrderByWithRelationInput | Prisma.UnsubscribeTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UnsubscribeTokens.
   */
  cursor?: Prisma.UnsubscribeTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnsubscribeTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnsubscribeTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UnsubscribeTokens.
   */
  distinct?: Prisma.UnsubscribeTokenScalarFieldEnum | Prisma.UnsubscribeTokenScalarFieldEnum[]
}

/**
 * UnsubscribeToken findFirstOrThrow
 */
export type UnsubscribeTokenFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenInclude<ExtArgs> | null
  /**
   * Filter, which UnsubscribeToken to fetch.
   */
  where?: Prisma.UnsubscribeTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnsubscribeTokens to fetch.
   */
  orderBy?: Prisma.UnsubscribeTokenOrderByWithRelationInput | Prisma.UnsubscribeTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UnsubscribeTokens.
   */
  cursor?: Prisma.UnsubscribeTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnsubscribeTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnsubscribeTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UnsubscribeTokens.
   */
  distinct?: Prisma.UnsubscribeTokenScalarFieldEnum | Prisma.UnsubscribeTokenScalarFieldEnum[]
}

/**
 * UnsubscribeToken findMany
 */
export type UnsubscribeTokenFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenInclude<ExtArgs> | null
  /**
   * Filter, which UnsubscribeTokens to fetch.
   */
  where?: Prisma.UnsubscribeTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnsubscribeTokens to fetch.
   */
  orderBy?: Prisma.UnsubscribeTokenOrderByWithRelationInput | Prisma.UnsubscribeTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UnsubscribeTokens.
   */
  cursor?: Prisma.UnsubscribeTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnsubscribeTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnsubscribeTokens.
   */
  skip?: number
  distinct?: Prisma.UnsubscribeTokenScalarFieldEnum | Prisma.UnsubscribeTokenScalarFieldEnum[]
}

/**
 * UnsubscribeToken create
 */
export type UnsubscribeTokenCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenInclude<ExtArgs> | null
  /**
   * The data needed to create a UnsubscribeToken.
   */
  data: Prisma.XOR<Prisma.UnsubscribeTokenCreateInput, Prisma.UnsubscribeTokenUncheckedCreateInput>
}

/**
 * UnsubscribeToken createMany
 */
export type UnsubscribeTokenCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UnsubscribeTokens.
   */
  data: Prisma.UnsubscribeTokenCreateManyInput | Prisma.UnsubscribeTokenCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UnsubscribeToken createManyAndReturn
 */
export type UnsubscribeTokenCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * The data used to create many UnsubscribeTokens.
   */
  data: Prisma.UnsubscribeTokenCreateManyInput | Prisma.UnsubscribeTokenCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UnsubscribeToken update
 */
export type UnsubscribeTokenUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenInclude<ExtArgs> | null
  /**
   * The data needed to update a UnsubscribeToken.
   */
  data: Prisma.XOR<Prisma.UnsubscribeTokenUpdateInput, Prisma.UnsubscribeTokenUncheckedUpdateInput>
  /**
   * Choose, which UnsubscribeToken to update.
   */
  where: Prisma.UnsubscribeTokenWhereUniqueInput
}

/**
 * UnsubscribeToken updateMany
 */
export type UnsubscribeTokenUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UnsubscribeTokens.
   */
  data: Prisma.XOR<Prisma.UnsubscribeTokenUpdateManyMutationInput, Prisma.UnsubscribeTokenUncheckedUpdateManyInput>
  /**
   * Filter which UnsubscribeTokens to update
   */
  where?: Prisma.UnsubscribeTokenWhereInput
  /**
   * Limit how many UnsubscribeTokens to update.
   */
  limit?: number
}

/**
 * UnsubscribeToken updateManyAndReturn
 */
export type UnsubscribeTokenUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * The data used to update UnsubscribeTokens.
   */
  data: Prisma.XOR<Prisma.UnsubscribeTokenUpdateManyMutationInput, Prisma.UnsubscribeTokenUncheckedUpdateManyInput>
  /**
   * Filter which UnsubscribeTokens to update
   */
  where?: Prisma.UnsubscribeTokenWhereInput
  /**
   * Limit how many UnsubscribeTokens to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UnsubscribeToken upsert
 */
export type UnsubscribeTokenUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenInclude<ExtArgs> | null
  /**
   * The filter to search for the UnsubscribeToken to update in case it exists.
   */
  where: Prisma.UnsubscribeTokenWhereUniqueInput
  /**
   * In case the UnsubscribeToken found by the `where` argument doesn't exist, create a new UnsubscribeToken with this data.
   */
  create: Prisma.XOR<Prisma.UnsubscribeTokenCreateInput, Prisma.UnsubscribeTokenUncheckedCreateInput>
  /**
   * In case the UnsubscribeToken was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UnsubscribeTokenUpdateInput, Prisma.UnsubscribeTokenUncheckedUpdateInput>
}

/**
 * UnsubscribeToken delete
 */
export type UnsubscribeTokenDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenInclude<ExtArgs> | null
  /**
   * Filter which UnsubscribeToken to delete.
   */
  where: Prisma.UnsubscribeTokenWhereUniqueInput
}

/**
 * UnsubscribeToken deleteMany
 */
export type UnsubscribeTokenDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UnsubscribeTokens to delete
   */
  where?: Prisma.UnsubscribeTokenWhereInput
  /**
   * Limit how many UnsubscribeTokens to delete.
   */
  limit?: number
}

/**
 * UnsubscribeToken without action
 */
export type UnsubscribeTokenDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnsubscribeToken
   */
  select?: Prisma.UnsubscribeTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnsubscribeToken
   */
  omit?: Prisma.UnsubscribeTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnsubscribeTokenInclude<ExtArgs> | null
}
