
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserMute` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UserMute
 * 
 */
export type UserMuteModel = runtime.Types.Result.DefaultSelection<Prisma.$UserMutePayload>

export type AggregateUserMute = {
  _count: UserMuteCountAggregateOutputType | null
  _avg: UserMuteAvgAggregateOutputType | null
  _sum: UserMuteSumAggregateOutputType | null
  _min: UserMuteMinAggregateOutputType | null
  _max: UserMuteMaxAggregateOutputType | null
}

export type UserMuteAvgAggregateOutputType = {
  id: number | null
  muterId: number | null
  mutedId: number | null
}

export type UserMuteSumAggregateOutputType = {
  id: number | null
  muterId: number | null
  mutedId: number | null
}

export type UserMuteMinAggregateOutputType = {
  id: number | null
  muterId: number | null
  mutedId: number | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type UserMuteMaxAggregateOutputType = {
  id: number | null
  muterId: number | null
  mutedId: number | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type UserMuteCountAggregateOutputType = {
  id: number
  muterId: number
  mutedId: number
  expiresAt: number
  createdAt: number
  _all: number
}


export type UserMuteAvgAggregateInputType = {
  id?: true
  muterId?: true
  mutedId?: true
}

export type UserMuteSumAggregateInputType = {
  id?: true
  muterId?: true
  mutedId?: true
}

export type UserMuteMinAggregateInputType = {
  id?: true
  muterId?: true
  mutedId?: true
  expiresAt?: true
  createdAt?: true
}

export type UserMuteMaxAggregateInputType = {
  id?: true
  muterId?: true
  mutedId?: true
  expiresAt?: true
  createdAt?: true
}

export type UserMuteCountAggregateInputType = {
  id?: true
  muterId?: true
  mutedId?: true
  expiresAt?: true
  createdAt?: true
  _all?: true
}

export type UserMuteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserMute to aggregate.
   */
  where?: Prisma.UserMuteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserMutes to fetch.
   */
  orderBy?: Prisma.UserMuteOrderByWithRelationInput | Prisma.UserMuteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserMuteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserMutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserMutes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserMutes
  **/
  _count?: true | UserMuteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserMuteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserMuteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMuteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMuteMaxAggregateInputType
}

export type GetUserMuteAggregateType<T extends UserMuteAggregateArgs> = {
      [P in keyof T & keyof AggregateUserMute]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserMute[P]>
    : Prisma.GetScalarType<T[P], AggregateUserMute[P]>
}




export type UserMuteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserMuteWhereInput
  orderBy?: Prisma.UserMuteOrderByWithAggregationInput | Prisma.UserMuteOrderByWithAggregationInput[]
  by: Prisma.UserMuteScalarFieldEnum[] | Prisma.UserMuteScalarFieldEnum
  having?: Prisma.UserMuteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserMuteCountAggregateInputType | true
  _avg?: UserMuteAvgAggregateInputType
  _sum?: UserMuteSumAggregateInputType
  _min?: UserMuteMinAggregateInputType
  _max?: UserMuteMaxAggregateInputType
}

export type UserMuteGroupByOutputType = {
  id: number
  muterId: number
  mutedId: number
  expiresAt: Date | null
  createdAt: Date
  _count: UserMuteCountAggregateOutputType | null
  _avg: UserMuteAvgAggregateOutputType | null
  _sum: UserMuteSumAggregateOutputType | null
  _min: UserMuteMinAggregateOutputType | null
  _max: UserMuteMaxAggregateOutputType | null
}

type GetUserMuteGroupByPayload<T extends UserMuteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserMuteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserMuteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserMuteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserMuteGroupByOutputType[P]>
      }
    >
  >



export type UserMuteWhereInput = {
  AND?: Prisma.UserMuteWhereInput | Prisma.UserMuteWhereInput[]
  OR?: Prisma.UserMuteWhereInput[]
  NOT?: Prisma.UserMuteWhereInput | Prisma.UserMuteWhereInput[]
  id?: Prisma.IntFilter<"UserMute"> | number
  muterId?: Prisma.IntFilter<"UserMute"> | number
  mutedId?: Prisma.IntFilter<"UserMute"> | number
  expiresAt?: Prisma.DateTimeNullableFilter<"UserMute"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"UserMute"> | Date | string
}

export type UserMuteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  muterId?: Prisma.SortOrder
  mutedId?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserMuteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  muterId_mutedId?: Prisma.UserMuteMuterIdMutedIdCompoundUniqueInput
  AND?: Prisma.UserMuteWhereInput | Prisma.UserMuteWhereInput[]
  OR?: Prisma.UserMuteWhereInput[]
  NOT?: Prisma.UserMuteWhereInput | Prisma.UserMuteWhereInput[]
  muterId?: Prisma.IntFilter<"UserMute"> | number
  mutedId?: Prisma.IntFilter<"UserMute"> | number
  expiresAt?: Prisma.DateTimeNullableFilter<"UserMute"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"UserMute"> | Date | string
}, "id" | "muterId_mutedId">

export type UserMuteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  muterId?: Prisma.SortOrder
  mutedId?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.UserMuteCountOrderByAggregateInput
  _avg?: Prisma.UserMuteAvgOrderByAggregateInput
  _max?: Prisma.UserMuteMaxOrderByAggregateInput
  _min?: Prisma.UserMuteMinOrderByAggregateInput
  _sum?: Prisma.UserMuteSumOrderByAggregateInput
}

export type UserMuteScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserMuteScalarWhereWithAggregatesInput | Prisma.UserMuteScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserMuteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserMuteScalarWhereWithAggregatesInput | Prisma.UserMuteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"UserMute"> | number
  muterId?: Prisma.IntWithAggregatesFilter<"UserMute"> | number
  mutedId?: Prisma.IntWithAggregatesFilter<"UserMute"> | number
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"UserMute"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserMute"> | Date | string
}

export type UserMuteCreateInput = {
  muterId: number
  mutedId: number
  expiresAt?: Date | string | null
  createdAt?: Date | string
}

export type UserMuteUncheckedCreateInput = {
  id?: number
  muterId: number
  mutedId: number
  expiresAt?: Date | string | null
  createdAt?: Date | string
}

export type UserMuteUpdateInput = {
  muterId?: Prisma.IntFieldUpdateOperationsInput | number
  mutedId?: Prisma.IntFieldUpdateOperationsInput | number
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserMuteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  muterId?: Prisma.IntFieldUpdateOperationsInput | number
  mutedId?: Prisma.IntFieldUpdateOperationsInput | number
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserMuteCreateManyInput = {
  id?: number
  muterId: number
  mutedId: number
  expiresAt?: Date | string | null
  createdAt?: Date | string
}

export type UserMuteUpdateManyMutationInput = {
  muterId?: Prisma.IntFieldUpdateOperationsInput | number
  mutedId?: Prisma.IntFieldUpdateOperationsInput | number
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserMuteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  muterId?: Prisma.IntFieldUpdateOperationsInput | number
  mutedId?: Prisma.IntFieldUpdateOperationsInput | number
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserMuteMuterIdMutedIdCompoundUniqueInput = {
  muterId: number
  mutedId: number
}

export type UserMuteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  muterId?: Prisma.SortOrder
  mutedId?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserMuteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  muterId?: Prisma.SortOrder
  mutedId?: Prisma.SortOrder
}

export type UserMuteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  muterId?: Prisma.SortOrder
  mutedId?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserMuteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  muterId?: Prisma.SortOrder
  mutedId?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserMuteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  muterId?: Prisma.SortOrder
  mutedId?: Prisma.SortOrder
}



export type UserMuteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  muterId?: boolean
  mutedId?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["userMute"]>

export type UserMuteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  muterId?: boolean
  mutedId?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["userMute"]>

export type UserMuteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  muterId?: boolean
  mutedId?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["userMute"]>

export type UserMuteSelectScalar = {
  id?: boolean
  muterId?: boolean
  mutedId?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}

export type UserMuteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "muterId" | "mutedId" | "expiresAt" | "createdAt", ExtArgs["result"]["userMute"]>

export type $UserMutePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserMute"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    muterId: number
    mutedId: number
    expiresAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["userMute"]>
  composites: {}
}

export type UserMuteGetPayload<S extends boolean | null | undefined | UserMuteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserMutePayload, S>

export type UserMuteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserMuteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserMuteCountAggregateInputType | true
  }

export interface UserMuteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserMute'], meta: { name: 'UserMute' } }
  /**
   * Find zero or one UserMute that matches the filter.
   * @param {UserMuteFindUniqueArgs} args - Arguments to find a UserMute
   * @example
   * // Get one UserMute
   * const userMute = await prisma.userMute.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserMuteFindUniqueArgs>(args: Prisma.SelectSubset<T, UserMuteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserMuteClient<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserMute that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserMuteFindUniqueOrThrowArgs} args - Arguments to find a UserMute
   * @example
   * // Get one UserMute
   * const userMute = await prisma.userMute.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserMuteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserMuteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserMuteClient<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserMute that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMuteFindFirstArgs} args - Arguments to find a UserMute
   * @example
   * // Get one UserMute
   * const userMute = await prisma.userMute.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserMuteFindFirstArgs>(args?: Prisma.SelectSubset<T, UserMuteFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserMuteClient<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserMute that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMuteFindFirstOrThrowArgs} args - Arguments to find a UserMute
   * @example
   * // Get one UserMute
   * const userMute = await prisma.userMute.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserMuteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserMuteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserMuteClient<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserMutes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMuteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserMutes
   * const userMutes = await prisma.userMute.findMany()
   * 
   * // Get first 10 UserMutes
   * const userMutes = await prisma.userMute.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userMuteWithIdOnly = await prisma.userMute.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserMuteFindManyArgs>(args?: Prisma.SelectSubset<T, UserMuteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserMute.
   * @param {UserMuteCreateArgs} args - Arguments to create a UserMute.
   * @example
   * // Create one UserMute
   * const UserMute = await prisma.userMute.create({
   *   data: {
   *     // ... data to create a UserMute
   *   }
   * })
   * 
   */
  create<T extends UserMuteCreateArgs>(args: Prisma.SelectSubset<T, UserMuteCreateArgs<ExtArgs>>): Prisma.Prisma__UserMuteClient<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserMutes.
   * @param {UserMuteCreateManyArgs} args - Arguments to create many UserMutes.
   * @example
   * // Create many UserMutes
   * const userMute = await prisma.userMute.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserMuteCreateManyArgs>(args?: Prisma.SelectSubset<T, UserMuteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserMutes and returns the data saved in the database.
   * @param {UserMuteCreateManyAndReturnArgs} args - Arguments to create many UserMutes.
   * @example
   * // Create many UserMutes
   * const userMute = await prisma.userMute.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserMutes and only return the `id`
   * const userMuteWithIdOnly = await prisma.userMute.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserMuteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserMuteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserMute.
   * @param {UserMuteDeleteArgs} args - Arguments to delete one UserMute.
   * @example
   * // Delete one UserMute
   * const UserMute = await prisma.userMute.delete({
   *   where: {
   *     // ... filter to delete one UserMute
   *   }
   * })
   * 
   */
  delete<T extends UserMuteDeleteArgs>(args: Prisma.SelectSubset<T, UserMuteDeleteArgs<ExtArgs>>): Prisma.Prisma__UserMuteClient<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserMute.
   * @param {UserMuteUpdateArgs} args - Arguments to update one UserMute.
   * @example
   * // Update one UserMute
   * const userMute = await prisma.userMute.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserMuteUpdateArgs>(args: Prisma.SelectSubset<T, UserMuteUpdateArgs<ExtArgs>>): Prisma.Prisma__UserMuteClient<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserMutes.
   * @param {UserMuteDeleteManyArgs} args - Arguments to filter UserMutes to delete.
   * @example
   * // Delete a few UserMutes
   * const { count } = await prisma.userMute.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserMuteDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserMuteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserMutes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMuteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserMutes
   * const userMute = await prisma.userMute.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserMuteUpdateManyArgs>(args: Prisma.SelectSubset<T, UserMuteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserMutes and returns the data updated in the database.
   * @param {UserMuteUpdateManyAndReturnArgs} args - Arguments to update many UserMutes.
   * @example
   * // Update many UserMutes
   * const userMute = await prisma.userMute.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserMutes and only return the `id`
   * const userMuteWithIdOnly = await prisma.userMute.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserMuteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserMuteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserMute.
   * @param {UserMuteUpsertArgs} args - Arguments to update or create a UserMute.
   * @example
   * // Update or create a UserMute
   * const userMute = await prisma.userMute.upsert({
   *   create: {
   *     // ... data to create a UserMute
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserMute we want to update
   *   }
   * })
   */
  upsert<T extends UserMuteUpsertArgs>(args: Prisma.SelectSubset<T, UserMuteUpsertArgs<ExtArgs>>): Prisma.Prisma__UserMuteClient<runtime.Types.Result.GetResult<Prisma.$UserMutePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserMutes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMuteCountArgs} args - Arguments to filter UserMutes to count.
   * @example
   * // Count the number of UserMutes
   * const count = await prisma.userMute.count({
   *   where: {
   *     // ... the filter for the UserMutes we want to count
   *   }
   * })
  **/
  count<T extends UserMuteCountArgs>(
    args?: Prisma.Subset<T, UserMuteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserMuteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserMute.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMuteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserMuteAggregateArgs>(args: Prisma.Subset<T, UserMuteAggregateArgs>): Prisma.PrismaPromise<GetUserMuteAggregateType<T>>

  /**
   * Group by UserMute.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMuteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserMuteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserMuteGroupByArgs['orderBy'] }
      : { orderBy?: UserMuteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserMuteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserMuteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserMute model
 */
readonly fields: UserMuteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserMute.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserMuteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserMute model
 */
export interface UserMuteFieldRefs {
  readonly id: Prisma.FieldRef<"UserMute", 'Int'>
  readonly muterId: Prisma.FieldRef<"UserMute", 'Int'>
  readonly mutedId: Prisma.FieldRef<"UserMute", 'Int'>
  readonly expiresAt: Prisma.FieldRef<"UserMute", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"UserMute", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserMute findUnique
 */
export type UserMuteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * Filter, which UserMute to fetch.
   */
  where: Prisma.UserMuteWhereUniqueInput
}

/**
 * UserMute findUniqueOrThrow
 */
export type UserMuteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * Filter, which UserMute to fetch.
   */
  where: Prisma.UserMuteWhereUniqueInput
}

/**
 * UserMute findFirst
 */
export type UserMuteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * Filter, which UserMute to fetch.
   */
  where?: Prisma.UserMuteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserMutes to fetch.
   */
  orderBy?: Prisma.UserMuteOrderByWithRelationInput | Prisma.UserMuteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserMutes.
   */
  cursor?: Prisma.UserMuteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserMutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserMutes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserMutes.
   */
  distinct?: Prisma.UserMuteScalarFieldEnum | Prisma.UserMuteScalarFieldEnum[]
}

/**
 * UserMute findFirstOrThrow
 */
export type UserMuteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * Filter, which UserMute to fetch.
   */
  where?: Prisma.UserMuteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserMutes to fetch.
   */
  orderBy?: Prisma.UserMuteOrderByWithRelationInput | Prisma.UserMuteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserMutes.
   */
  cursor?: Prisma.UserMuteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserMutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserMutes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserMutes.
   */
  distinct?: Prisma.UserMuteScalarFieldEnum | Prisma.UserMuteScalarFieldEnum[]
}

/**
 * UserMute findMany
 */
export type UserMuteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * Filter, which UserMutes to fetch.
   */
  where?: Prisma.UserMuteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserMutes to fetch.
   */
  orderBy?: Prisma.UserMuteOrderByWithRelationInput | Prisma.UserMuteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserMutes.
   */
  cursor?: Prisma.UserMuteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserMutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserMutes.
   */
  skip?: number
  distinct?: Prisma.UserMuteScalarFieldEnum | Prisma.UserMuteScalarFieldEnum[]
}

/**
 * UserMute create
 */
export type UserMuteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * The data needed to create a UserMute.
   */
  data: Prisma.XOR<Prisma.UserMuteCreateInput, Prisma.UserMuteUncheckedCreateInput>
}

/**
 * UserMute createMany
 */
export type UserMuteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserMutes.
   */
  data: Prisma.UserMuteCreateManyInput | Prisma.UserMuteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserMute createManyAndReturn
 */
export type UserMuteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * The data used to create many UserMutes.
   */
  data: Prisma.UserMuteCreateManyInput | Prisma.UserMuteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserMute update
 */
export type UserMuteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * The data needed to update a UserMute.
   */
  data: Prisma.XOR<Prisma.UserMuteUpdateInput, Prisma.UserMuteUncheckedUpdateInput>
  /**
   * Choose, which UserMute to update.
   */
  where: Prisma.UserMuteWhereUniqueInput
}

/**
 * UserMute updateMany
 */
export type UserMuteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserMutes.
   */
  data: Prisma.XOR<Prisma.UserMuteUpdateManyMutationInput, Prisma.UserMuteUncheckedUpdateManyInput>
  /**
   * Filter which UserMutes to update
   */
  where?: Prisma.UserMuteWhereInput
  /**
   * Limit how many UserMutes to update.
   */
  limit?: number
}

/**
 * UserMute updateManyAndReturn
 */
export type UserMuteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * The data used to update UserMutes.
   */
  data: Prisma.XOR<Prisma.UserMuteUpdateManyMutationInput, Prisma.UserMuteUncheckedUpdateManyInput>
  /**
   * Filter which UserMutes to update
   */
  where?: Prisma.UserMuteWhereInput
  /**
   * Limit how many UserMutes to update.
   */
  limit?: number
}

/**
 * UserMute upsert
 */
export type UserMuteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * The filter to search for the UserMute to update in case it exists.
   */
  where: Prisma.UserMuteWhereUniqueInput
  /**
   * In case the UserMute found by the `where` argument doesn't exist, create a new UserMute with this data.
   */
  create: Prisma.XOR<Prisma.UserMuteCreateInput, Prisma.UserMuteUncheckedCreateInput>
  /**
   * In case the UserMute was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserMuteUpdateInput, Prisma.UserMuteUncheckedUpdateInput>
}

/**
 * UserMute delete
 */
export type UserMuteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
  /**
   * Filter which UserMute to delete.
   */
  where: Prisma.UserMuteWhereUniqueInput
}

/**
 * UserMute deleteMany
 */
export type UserMuteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserMutes to delete
   */
  where?: Prisma.UserMuteWhereInput
  /**
   * Limit how many UserMutes to delete.
   */
  limit?: number
}

/**
 * UserMute without action
 */
export type UserMuteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserMute
   */
  select?: Prisma.UserMuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserMute
   */
  omit?: Prisma.UserMuteOmit<ExtArgs> | null
}
